### ISSUE TITLE
How can I install and use this in an ember/ember-cli project?

### ISSUE THREAD

**Issue by erichonkanen** [testdouble/testdouble.js#105]
Hello,

I recently came across this lib and tried to use it in an Ember/Ember-CLI project (2.5) but could not figure it out. I used `npm install -g testdouble` and then tried to do `import td from 'testdouble/dist/testdouble`, also `import td from 'testdouble'`

How can I use this?

**Comment by searls** [comment]
Hey @erichonkanen thanks for the question. I don't have an Ember project handy but maybe @kpfefferle could help you out?

**Comment by AlexBlom** [comment]
I've started using TestDouble for ember-cordova & wrote a shim you can use.

https://github.com/isleofcode/ember-cli-testdouble

**Comment by searls** [comment]
Closing. Thanks @AlexBlom

**Comment by searls** [comment]
Just documented: https://github.com/testdouble/testdouble.js/commit/4c4c1b714911c685a756f0be07027d86fd731086
