### ISSUE TITLE
Flexible parameters

### ISSUE THREAD

**Issue by phzbox** [testdouble/testdouble.js#110]
Is there a matcher to return a value from literally any kind of parameters, such as:

 ```
  let f = td.func()
  td.when(f(???)).thenReturn('abc')
  
  f() // abc
  f('a') // abc
  f(1,2,3) // abc
```

The only way I found was to do:

```
  let f = td.func()
  let anything = td.matchers.anything
 
  td.when(f()).thenReturn('abc')
  td.when(f(anything())).thenReturn('abc')
  td.when(f(anything(), anything(), anything())).thenReturn('abc')
```

**Comment by searls** [comment]
You're looking for the `ignoreExtraArgs` Option. 

`td.when(f(), {ignoreExtraArgs: true}).thenReturen(5)` 

It's documented in the chapter on when stubbing
