### ISSUE TITLE
Improve error output message

### ISSUE THREAD

**Issue by emragins** [testdouble/testdouble.js#111]
```
TypeError: 'undefined' is not a function (evaluating '_.all(expectedArgs, function(expectedArg, i) {
	      return argumentMatchesExpectation(expectedArg, actualArgs[i]);
	    })')
```

My test runner (wallaby) gives me a stack trace, too, which is wrong.  I have no idea where this is happening in my code.  All I can tell is something's undefined somewhere......

PS
I'm a total novice to testdouble.js and I'm relatively new to JS testing in general.  I really like the philosophy of testdouble since already it's forced me to clean up a couple lazy decisions in my code.

**Comment by searls** [comment]
I am sorry but I don't think this is enough to go on. I think I need you to help us by providing the project or—much better still—a reproducible example. Until then I don't think we're going to have the time to try to reproduce it without more info.
