### ISSUE TITLE
td.replace doesn't properly detect ES6 classes

### ISSUE THREAD

**Issue by monkbroc** [testdouble/testdouble.js#119]
When using Node 6 with ES6 classes the `td.replace` call doesn't properly detect ES6 classes as constructors because the methods of ES6 classes are not enumerable. The constructor is not wrapped as expected.

The affected line is https://github.com/testdouble/testdouble.js/blob/65251fe625574aea0569140768f993641d53620f/src/replace/is-constructor.coffee#L5

Test case to reproduce:

```
# index.js
const td = require('testdouble');
const MyES5Class = td.replace('./MyES5Class');
const MyES6Class = td.replace('./MyES6Class');

td.when(MyES5Class.mymethod()).thenReturn(5); // <-- works
td.when(MyES6Class.mymethod()).thenReturn(6); // <-- MyES6Class.mymethod is not a function

# MyES5Class.js
function MyES5Class() {}
MyES5Class.prototype.mymethod = function () {
  return 0;
};

module.exports = MyES5Class;

# MyES6Class.js
class MyES6Class {
  constructor() {}
  mymethod() {
    return 0;
  }
}

module.exports = MyES6Class;
```

**Comment by searls** [comment]
Hey thanks for opening this!  Ideas on how to implement. I'm not very familiar with ES6 classes—what introspection is available?

**Comment by monkbroc** [comment]
I'm not so familiar with the inner workings of ES6 either. I found that `Object.getOwnPropertyNames()` returns both the enumerable and non-enumerable properties.

Based on some other issues I saw maybe the approach in `is-constructor` is flawed since it only looks for functions inside the prototype. It would be perfectly valid for a class to have no methods.

What about an approach like `thing.prototype.constructor === thing`

**Comment by monkbroc** [comment]
Here's a work in progress to catch ES6 classes:
```
// replace this:
//return _(thing.prototype).functions().any();

// by this:
var props = Object.getOwnPropertyNames(thing.prototype);
return _(props).map(function (p) { return p !== 'constructor' && _.isFunction(thing.prototype[p]); }).any();
```

**Comment by monkbroc** [comment]
I tried adding a test, but I don't know how that would work since the syntax would only compile in new Node...

https://github.com/monkbroc/testdouble.js/commit/773ecabecc71789b0e1cb32d81e2cc0abe158cc4

**Comment by searls** [comment]
Hat tip to @jasonkarns for finding this: https://github.com/boopathi/functions-in-es6/blob/master/src/get-function-type.js

**Comment by jkozieronek** [comment]
Looking forward to this enhancement. Just started using testdouble and like it a lot compared to sinon.

**Comment by searls** [comment]
Could you please re-test following merger of this & the ES2015 class example in `example/babel` directory? https://github.com/testdouble/testdouble.js/pull/130

If that example is insufficient, a great start would be to add failing examples to it.

**Comment by searls** [comment]
FYI that I am finally looking at this in #158 -- I cherry-picked your WIP
