### ISSUE TITLE
Question with verifications

### ISSUE THREAD

**Issue by josh-egan-ps** [testdouble/testdouble.js#138]
Just a question - is it possible to avoid the warning log message when doing a verification on a stubbed method with no parameters?

Our team prefers to do verifications (log output is better making failed tests easier to diagnose). So this is common for us:

```js
beforeEach(() => {
  td.replace(courseRepository, 'get')
  td.when(courseRepository.get(td.matchers.anything())).thenResolve(courseDto)

  return courseFacade.getCourse(id).then(r => actual = r)
})

it('should load the course from the repository', () => {
  td.verify(courseRepository.get({where: {id}}))
})
```

So when we have a method that doesn't take any arguments, we get the warning output to our console. e.g.

```js
beforeEach(() => {
  td.replace(mentorshipFacade, 'getTags')
  td.when(mentorshipFacade.getTags()).thenResolve(mentorshipTags)

  return courseFacade.getCourse(id).then(r => actual = r)
})

it('should get the mentorship tags', () => {
  td.verify(mentorshipFacade.getTags())
})
```

**Comment by searls** [comment]
I'd like to separate two aspects of this issue:

1. First, the fact that the warning is only firing for no-arg invocations isn't right. It should be firing for any case where a method is both stubbed and verified. If you're seeing this, then that's a bug and should be fixed! 🐞 

2. The warning is there exactly to discourage this style of testing; if the stubbing is necessary for the code to work, then the code ought to be able to be verified by some other means (e.g.  return value or a call sent to some other method). A few sub-notes:
  * If you really want, you can disable the warnings [as shown here](https://github.com/testdouble/testdouble.js/blob/master/docs/C-configuration.md#tdconfig)
  * If you're willing to share what you mean by "making failed tests easier to diagnose" with a runnable example, I'd appreciate it.
  * Could you share the production source code for this test example? I suspect there's a different way to design the test that would obviate the need for stubbing & verifying it

**Comment by josh-egan-ps** [comment]
Thanks for the reply, @searls.

1. 

The way that this was working didn't seem like a bug to me, but if it is, then I guess a change is forthcoming. :) I have found that the warning does not fire when `td.matchers.anything()` or `{ignoreExtraArgs: true}` is used. 

So, for example:

```js
// this DOES NOT fire a warning when later using td.verify
td.when(courseRepository.get(td.matchers.anything())).thenResolve(courseDto)
td.when(courseRepository.get(), {ignoreExtraArgs: true}).thenResolve(courseDto)

// this DOES fire a warning when later using td.verify
const id = 'foo'
td.when(courseRepository.get(id)).thenResolve(courseDto)
```

2.

Here's an example of why the verification style testing has been easier for us to diagnose. This example mirrors the production objects and interfaces that prompted me to ask this question, so hopefully this should suffice. The difference between this example and the production code is that this example is self-contained (a single file rather than having to `require` a bunch of files).

```js
// using mocha.js as a test runner and node 6.3.1 (no babel)

describe.only('testdouble warning demo', () => {
  const courseRepo = {
    get(queryOptions) {
      return Promise.reject(new Error('not implemented!'))
    }
  }

  const tagsRepo = {
    getTags() {
      return Promise.reject(new Error('not implemented'))
    }
  }

  const vmBuilder = {
    buildCourseVm(course, tags) {
      throw new Error('not implemented')
    }
  }

  afterEach(() => {
    td.reset()
  })

  context('when the subject under test does not contain the correct logic', () => {
    /* There are two errors in this implementation which are not obvious from just 
       reading the implementation code.
       
       Will the error output from the tests quickly point us to the errors in this code?
    */
    const subject = {
      getCourse(id) {
        return Promise.all([
          courseRepo.get(id),
          tagsRepo.getTags()
        ])
          .then(results => vmBuilder.buildCourseVm(results[1], results[0]))
      }
    }

    context('when matchers and td.verify are NOT used', () => {
      let result, expectedVm

      beforeEach(() => {
        const id = 'd8fadijvojzliliejvasd'
        const course = {id: 'aosfjasfdadofjsdfoiasdjfaoseijar', title: 'isojf9a3ur9jfazklfjaf'}
        const tags = ['1234ljk123klj', '989812349889', 'zzxcvklzxvjd']
        
        expectedVm = {id: 'dkdkdkdkdkd'}

        td.replace(courseRepo, 'get')
        td.when(courseRepo.get({where: {id}})).thenResolve(course)

        td.replace(tagsRepo, 'getTags')
        td.when(tagsRepo.getTags()).thenResolve(tags)

        td.replace(vmBuilder, 'buildCourseVm')
        td.when(vmBuilder.buildCourseVm(course, tags)).thenReturn(expectedVm)

        return subject.getCourse(id).then(r => result = r)
      })

      it('should return the correct vm', () => {
        expect(result).to.eql(expectedVm)
      })
    })

    context('when matchers and td.verify ARE used', () => {
      let result, id, course, tags, expectedVm

      beforeEach(() => {
        id = 'd8fadijvojzliliejvasd'
        course = {id: 'aosfjasfdadofjsdfoiasdjfaoseijar', title: 'isojf9a3ur9jfazklfjaf'}
        tags = ['1234ljk123klj', '989812349889', 'zzxcvklzxvjd']

        expectedVm = {id: 'dkdkdkdkdkd'}

        td.replace(courseRepo, 'get')
        td.when(courseRepo.get(td.matchers.anything())).thenResolve(course)

        td.replace(tagsRepo, 'getTags')
        td.when(tagsRepo.getTags()).thenResolve(tags)

        td.replace(vmBuilder, 'buildCourseVm')
        td.when(vmBuilder.buildCourseVm(), {ignoreExtraArgs: true}).thenReturn(expectedVm)

        return subject.getCourse(id).then(r => result = r)
      })

      it('should get the course from the repo', () => {
        td.verify(courseRepo.get({where: {id}}))
      })

      it('should get the tags from the repo', () => {
        td.verify(tagsRepo.getTags())
      })

      it('should call the vm builder', () => {
        td.verify(vmBuilder.buildCourseVm(course, tags))
      })

      it('should return the correct vm', () => {
        expect(result).to.eql(expectedVm)
      })
    })
  })
})
```

```bash
  [▬▬․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․]Warning: testdouble.js - td.verify - test double `getTags` was both stubbed and verified with arguments (), which is redundant and probably unnecessary. (see: https://github.com/testdouble/testdouble.js/blob/master/docs/B-frequently-asked-questions.md#why-shouldnt-i-call-both-tdwhen-and-tdverify-for-a-single-interaction-with-a-test-double )
  [▬▬▬▬▬▬․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․]

  2 passing (18ms)
  3 failing

  1) testdouble warning demo when the subject under test does not contain the correct logic when matchers and td.verify are NOT used should return the correct vm:
     AssertionError: expected undefined to deeply equal { id: 'dkdkdkdkdkd' }
      at Context.it (src/courses/course-facade.specs.js:72:27)

  2) testdouble warning demo when the subject under test does not contain the correct logic when matchers and td.verify ARE used should get the course from the repo:
     Error: Unsatisfied verification on test double `get`.

  Wanted:
    - called with `({where: {id: "d8fadijvojzliliejvasd"}})`.

  But was actually called:
    - called with `("d8fadijvojzliliejvasd")`.
      at Object.module.exports.fail (node_modules/testdouble/lib/log.js:21:13)
      at Object.module.exports [as verify] (node_modules/testdouble/lib/verify.js:28:20)
      at Context.it (src/courses/course-facade.specs.js:98:12)

  3) testdouble warning demo when the subject under test does not contain the correct logic when matchers and td.verify ARE used should call the vm builder:
     Error: Unsatisfied verification on test double `buildCourseVm`.

  Wanted:
    - called with `({
  id: "aosfjasfdadofjsdfoiasdjfaoseijar",
  title: "isojf9a3ur9jfazklfjaf"
}, ["1234ljk123klj", "989812349889", "zzxcvklzxvjd"])`.

  But was actually called:
    - called with `(["1234ljk123klj", "989812349889", "zzxcvklzxvjd"], {
  id: "aosfjasfdadofjsdfoiasdjfaoseijar",
  title: "isojf9a3ur9jfazklfjaf"
})`.
      at Object.module.exports.fail (node_modules/testdouble/lib/log.js:21:13)
      at Object.module.exports [as verify] (node_modules/testdouble/lib/verify.js:28:20)
      at Context.it (src/courses/course-facade.specs.js:106:12)
```

So you can see from the output that using stubs without verifications results in a failure message of `expected undefined to deeply equal { id: 'dkdkdkdkdkd' }`, which isn't super helpful. Now I have to go comb through the code, and perhaps toggle tests on and off, to try to figure out exactly where that pesky undefined is coming from. In this, case, there are actually two errors, but I have no indication of that yet.

Using `td.matchers.anything()` in combination with `td.verify` on the other hand yields very detailed error messages. Reading the error messages immediately tells me I have two problems:
1. My input to the `courseRepo.get` method is not correctly formed. It should be a query options object.
2. The parameters I'm passing into the `vmBuilder.buildCourseVm` are not in the correct order.

So that's why we've been using testdouble with matchers and verifications. Another thing to point out, is that we intentionally use the `anything()` matcher so that the stub will return what it's supposed to return regardless of the inputs it receives. This makes it so that the first line can have an error, but the following lines still execute correctly. The td.verify can then point us directly to the call that was made in error, whether it was the first call or the last call.

Another common problem we had when using stubs was getting an error message of `TypeError: Cannot read property 'then' of undefined`, which over time I learned meant that we had something stubbed with `.thenResolve`, and we weren't passing in the correct parameters, so undefined was getting returned instead of a promise. This also often required detailed digging through the code. 

When writing new code using TDD, this is not a huge issue, because the tests and the logic are built up incrementally, and the error can quickly be discovered even if the error message is vague. However, having low quality error messages quickly becomes an issue when refactoring a file that's been sitting around for 6 months and all of a sudden the tests are failing with unhelpful messages.

With all of that being said, I'm wide open to any ideas you have for writing tests differently. This is what we have found has yielded the best error output for us, but I'm open to a different way, especially if the output is even better! Our ultimate goal is to have tests that yield excellent error messages and get us to the point of failure as quickly as possible.

**Comment by searls** [comment]
I sat with your code for quite a while, and I definitely see your point. My primary focus with the library has been to facilitate writing focused tests with isolated TDD in mind. As you mentioned, the feedback you get is less of an issue when you're driving out a fresh object.

But your point that the `undefined != foo` is less clear than a longer verification error is also entirely valid. I think my best response to that would be that there are two general approaches to solving for a lack of good feedback from the failure:

1. Stricter mock objects that blow up when they encounter unexpected inputs. I avoid mocks because they violate arrange-act-assert and further constrain the subject's implementation, but the aggressive message-raising is a benefit to them that you'd see in this case

2. Intermediate assertions, like you have here, where you assert the final result, but you also assert things at intermediate points, to ensure you'll get a better message. This is a lot of extra code, can confuse readers as to the intention of the method (since every assertion is going to look like an outcome the code should have). In general I try to avoid intermediate assertions

3. When faced with insufficient assertion messages (like you are here), consider printing/debugging for the information you need and then once you have a handle of what is going on, delete any artifacts as opposed to committing them. This avoids saddling the codebase with unnecessarily-strict assertions, and is what I had in mind for `td.explain`

So faced with the same situation you just described, I dropped a `console.log` like this:

```js
      it('should return the correct vm', () => {
        console.log(td.explain(courseRepo.get).description)
        expect(result).to.eql(expectedVm)
      })
```

And then saw it print:

```
This test double `get` has 1 stubbings and 1 invocations.

Stubbings:
  - when called with `({where: {id: "d8fadijvojzliliejvasd"}})`, then resolve `{
  id: "aosfjasfdadofjsdfoiasdjfaoseijar",
  title: "isojf9a3ur9jfazklfjaf"
}`.

Invocations:
  - called with `("d8fadijvojzliliejvasd")`.
```

Which was enough for me to see the `{where: {id: 1}}` wrapper was missing. Then I made the fix and deleted the console logger.

That would be my recommended approach using td.js, and anything else would, I'm afraid, require a dramatic overhaul to the td.js library. If you still prefer the path you're on, then I would encourage you to just suppress warnings and move on.
