### ISSUE TITLE
Support multiple capture invocations

### ISSUE THREAD

**Issue by marchaos** [testdouble/testdouble.js#139]
Hey, 
I'm pretty sure this currently isn't supported, but it would be nice to allow for captures to capture multiple calls to the same method. See this example of mockito:

http://stackoverflow.com/questions/5981605/can-mockito-capture-arguments-of-a-method-called-multiple-times

I guess the API would need something similar where you can call capture.getAllValues()

**Comment by marchaos** [comment]
Please see https://github.com/marchaos/testdouble.js/blob/master/src/matchers/captor.coffee. This works for me. If there is only one invocation, the captor.value contains the captured value, otherwise captor.value is an array of all calls in the order the occurred. This allows for some backwards compatibility.

**Comment by searls** [comment]
I'm struggling to imagine very many examples where this would be needed. Can you think of a not-far-fetched example?

**Comment by marchaos** [comment]
It's a common pattern in streaming applications. I have a callback that is called whenever a message is received from a streaming source. 

In my usecase, I mock multiple messages of different types to ensure the underlying code handles those accordingly. This needs to be occur in 1 unit test as messages come in on batch. In my captor, I catch each processed message and assert that they contain the correct values.

**Comment by searls** [comment]
Okay. I think I can get behind adding a `values` attribute that shows all captured invocations and leave `value` as whatever the most-recent one was. That seems reasonable to me, since it wouldn't break back-compat. Do you agree?

**Comment by marchaos** [comment]
Hi Justin, yep that sounds like a plan. Do you want me to create a PR for this?

**Comment by searls** [comment]
Yeah, please feel free

**Comment by marchaos** [comment]
https://github.com/testdouble/testdouble.js/pull/144

**Comment by searls** [comment]
This landed in testdouble@1.8.0 for anyone keeping score.
