### ISSUE TITLE
Drop CoffeeScript

### ISSUE THREAD

**Issue by Moeriki** [testdouble/testdouble.js#140]
Is there any interest to drop CoffeeScript in favour of plain old ES2015+.

* CoffeeScript has had its run
* CoffeeScript limits contributions (speaking for myself especially)

**Comment by marchaos** [comment]
+1

**Comment by searls** [comment]
I'd consider a PR that converted the codebase to ES6, but as it is the library is mature and there's no appreciable impact on users.
