### ISSUE TITLE
A little typo in Getting Started documentation

### ISSUE THREAD

**Issue by gamtiq** [testdouble/testdouble.js#165]
A `)` is missing in the following sentence inside [Getting Started](https://github.com/testdouble/testdouble.js/blob/master/docs/3-getting-started.md#verifying-some-behavior) documentation page:
> By saying *td.verify(submitProblem('saved problem')*, we're telling testdouble.js to throw an error unless submitProblem is invoked with exactly one argument: 'saved problem'.

**Comment by searls** [comment]
Thanks, fixed
