### ISSUE TITLE
Is it possible to `thenReturn` the receiver?

### ISSUE THREAD

**Issue by aexmachina** [testdouble/testdouble.js#182]
I have a class that returns `this` to support chaining, but I can't see how to specify that the mock should `thenReturn` the receiver (`this`). Is this supported?

```js
class Model {
  save() {
    // save things
    return this
  }
}

let save = td.replace(Model.prototype, 'save')
td.when(save()).thenReturnThis() // how can I return the receiver?
```

**Comment by searls** [comment]
You could try:

```js
td.when(save()).thenDo(function () { return this })
```

I've never needed this and am not confident we don't do something to hijack this, but worth a shot
