### ISSUE TITLE
Stubbing promises with thenResolve does not actually provide for anything in the callback

### ISSUE THREAD

**Issue by Mark-de-Haan** [testdouble/testdouble.js#189]
When I copy paste your example of using thenResolve to stub a Promise, I do not get any actual logging.

Your example:
```
var fetch = td.function()
td.when(fetch('/user')).thenResolve('Jane')

fetch('/user').then(function (value) {
  console.log(value) // prints "Jane"
})
```
Expected: Console log printing: Jane
Observed: No logging

-------------------------------------------------------------------
Using .then() will now result in a _undefined is not a constructor_ error

I expect the undefined error is caused by the fact that I do not have anything in the callback.
I thought it was my own clumsy code, but seeing as your example also does not work, could it be something else?

**Comment by searls** [comment]
Does your runtime have a native `Promise` object available? Perhaps we don't have a nice error message for that case and you're just blowing up.

In a runtime with one, I see this same example under `node`@6.9.2:

<img width="759" alt="screen shot 2017-02-21 at 9 47 22 am" src="https://cloud.githubusercontent.com/assets/79303/23169734/e1da55ac-f81a-11e6-879d-d54a9c97cba4.png">

So to resolve this you just need to tell `td` what `Promise` constructor to use (e.g. bluebird, RSVP, etc):

```js
td.config({
  promiseConstructor: require('bluebird')
})
```

**Comment by searls** [comment]
Please confirm my speculation and if so I'll open an issue for the error message

**Comment by Mark-de-Haan** [comment]
So I added 

```
     td.config({
        promiseConstructor: require('bluebird')
      })

      var fetch = td.function()
      td.when(fetch('/user')).thenResolve('Jane')

      fetch('/user').then(function (value) {
        console.log(value) // prints "Jane"
      })

```
inside my test

And now it Sometimes prints Jane, and sometimes it doesn't..

**Comment by searls** [comment]
(╯°□°）╯︵ ┻━┻ 

What runtime are you on?

**Comment by Mark-de-Haan** [comment]
If I understand you correctly,

Im using Karma to run my tests in PhantomJS, on Node v5.3.0

**Comment by searls** [comment]
You're probably seeing erratic, because bluebird promises will always defer the stack frame upon resolution, which means the test itself needs to be made async, so then you'll need a `done` callback to make sure the test actually finishes

**Comment by Mark-de-Haan** [comment]
Ok, done() not working, let me post my code, maybe you can spot what im doing wrong
```
describe('Testing actions', () => {
  it('do some stuff', done => {
    td.config({
      promiseConstructor: require('bluebird')
    })

    var fetch = td.function()
    td.when(fetch('/user')).thenResolve('Jane')

    fetch('/user').then((value) => {
      console.log(value) // prints "Jane"
    })

    done()
  })
})
```

Nothing is being printed. Using a standard Karma + mocha setup from the vue-cli starter kit. Nothing to fancy

**Comment by Mark-de-Haan** [comment]
So I discovered what is going wrong
It works when I run: `cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run`

But I edited the package.json to run: `cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --watch`

This is convenient cause my tests will fail during development. Problem is that with the --watch, it does not print Jane for some reason

**Comment by searls** [comment]
It sounds like this is an issue with your use of karma and not tdjs then, no?

**Comment by Mark-de-Haan** [comment]
Yes, when using --single-run the Promise stub works. So I will close this issue. Thanks for the help!
