### ISSUE TITLE
`constructor(someConstructorFunction)` not referenced in associated example

### ISSUE THREAD

**Issue by chrisneave** [testdouble/testdouble.js#213]
In the [constructor(someConstructorFunction)](https://github.com/testdouble/testdouble.js/blob/master/docs/4-creating-test-doubles.md#constructorsomeconstructorfunction) section of the documentation, the second code block does not use the described `td.constructor()` function to create `FakeDog`. Instead it uses `td.object()`.

Is this a typo or is `td.constructor()` not meant to be used in this context?

**Comment by searls** [comment]
Typo. The public API changed in 2.x and I missed this example. thanks!
