### ISSUE TITLE
Mocking external dependencies in Express app

### ISSUE THREAD

**Issue by alathon** [testdouble/testdouble.js#221]
I have an Express app with a route that makes a call to an external module; lets say it might look like this:

```js
const externalModule = require('../some/path');
const app = express.Router();
app.get('/some/route', function (res, req) {
  externalModule.doSomething(stuff).then(res.send(204));
});
```

I'd like to mock/stub out the call to that external module. However, I'm having trouble getting that to work.

I'm using `tape`, and as soon as *any* one of my tests run (which all instantiate/refer back to the same Express `app`), any attempt to use e.g. `supertest` to make a request to `/some/route` doesn't use the mock for `externalModule`. I'm assuming this is because it's already been instantiated/cached, and the relevant `require()` calls have already been made by the app in a previous test.

Am I trying to do something I shouldnt? Is there any easy way to do this? The only solution I've found that works for me is to run a pre-test file that essentially does a `td.replace(...)` **before** any tape tests run, and doesn't run `td.reset()` at any point. This feels really wrong, though, and fragile; if I had needed specific per-test behavior, this would've fallen apart.

**Comment by alathon** [comment]
Ah. Hm. This seems to be what I thought - I shouldn't be doing this (https://github.com/testdouble/contributing-tests/wiki/Don%27t-mock-what-you-don%27t-own). Closing the issue =)

**Comment by searls** [comment]
This should be fine, the trick is that the test has to `require` things inside a before each so testdouble/quibble can intercept it:

```js
var test = require('tape')
var td = require('testdouble')

test('blah', function (t) {
    var externalModule = td.replace('../lib/some/path')
    var subject = require('../lib/that/code/example/you/have/above')
    td.when(externalModule.doSomething(stuff).thenResolve('blah')
    
    subject.callThing()
})
```
