### ISSUE TITLE
When replacing a node library calling it from other modules does not work as expected

### ISSUE THREAD

**Issue by anotheredward** [testdouble/testdouble.js#225]
When trying to replace the uuid library:
Calls local to the test return what I expect, but calls from the module under test do not.

I've made a repo to demonstrate the issue I'm having here:
https://github.com/anotheredward/testDoubleDependencyIssue

Happy to take advice on how I could use the library better!

Thanks,
Edward

**Comment by searls** [comment]
Thanks for the example project!

**Comment by searls** [comment]
Fixed it. The issue is that you need to replace/require inside a `beforeEach` so that it can be unwound properly and the dependencies not cached. Here is the working test:


```js
'use strict'
/* global describe, it, beforeEach, afterEach */

const assert = require('assert')
const td = require('testdouble')
const uuidString = '12345678-1234-4123-1234-123456789012'

describe('getUuid', function () {
  var uuidMock, getUuid
  beforeEach(function () {
    uuidMock = td.replace('uuid')
    getUuid = require('./getUuid')

    td.when(uuidMock.v4()).thenReturn(uuidString)
  })

  it('local call should return the mocked value', function () {
    const result = uuidMock.v4()
    return assert.equal(result, uuidString)
  })

  it('call from required dependency should return the mocked value', function () {
    const result = getUuid()
    return assert.equal(result, uuidString)
  })

  afterEach(function () {
    td.reset()
  })
})
```

**Comment by anotheredward** [comment]
Thanks, that's amazing @searls ! Really appreciate the help.

**Comment by anotheredward** [comment]
I've run in to another similar issue with two layers of indirection instead of one that I can't seem to work out :(.

I've updated the repo to include your fix and an additional failing test for the case I am seeing now: https://github.com/anotheredward/testDoubleDependencyIssue

Thanks,
Edward

**Comment by searls** [comment]
I took a peek, but I can pretty confidently tell you this isn't supported. The goal of the library is to replace direct dependencies of the thing under test. Allowing the subject to have some sort-of-real dependencies that in turn may-or-may-not fake their own dependencies is a recipe for confusion and almost always leads to tests for which the value proposition is unclear upon later readings.

**Comment by searls** [comment]
(That is to say, in a test of getUuidIndirectly, one should replace the getUuid dependency, not the uuid module itself)

Recommend reading this: https://github.com/testdouble/contributing-tests/wiki/Don%27t-mock-what-you-don%27t-own

**Comment by anotheredward** [comment]
Thanks! I've read that article a couple of times, struggling a bit to with it, will keep reading and thinking.
Really appreciate the time you've put in here to help me out @searls :).
