### ISSUE TITLE
Stubbing chained API objects yields a warning

### ISSUE THREAD

**Issue by hbarcelos** [testdouble/testdouble.js#228]
I'm testing express-like route callbacks which receive a pair of parameters `req, res`.

The `res` object is chainable, so I can do the following:

```js
function someHandler(req, res) {
    return res.status(XXX).json(YYY);
}
```

This is a rather simple function, but you can get the idea.

Then, I'm testing like this:

```js
  const req = {
    query : {
      version : 'v1'
    }
  }
  const res = td.object({
    status(status) {
    },
    json() {
    }
  })

  td.when(res.status(td.matchers.isA(Number))).thenReturn(res) // this is needed to allow me use the chained calls

  subject.getCountries(req, res)

  td.verify(res.status(200))
  td.verify(res.json(td.matchers.anything()))
```

The test passes as I expected, but I get this warning:

> Warning: testdouble.js - td.verify - test double `.status` was both stubbed and verified with arguments (200), which is redundant and probably unnecessary. (see: https://github.com/testdouble/testdouble.js/blob/master/docs/B-frequently-asked-questions.md#why-shouldnt-i-call-both-tdwhen-and-tdverify-for-a-single-interaction-with-a-test-double )

If I try to remove the `td.when(res.status(td.matchers.isA(Number))).thenReturn(res)` line, I get an error:

>  12:   const countryList =  finder.findCountries(geoDataToUse)
>  13:   res.status(200).json(countryList)
>  14: }
>
>  Error: Cannot read property 'json' of undefined

So, I was wondering if there is any way around this...

Thank's.

**Comment by searls** [comment]
First, I would advise strongly against trying to write an isolated unit test with testdouble.js of a third-party dependency like an express handler with chainable args. The pain you're experience is useless pain, because it can't drive you to improve the design of the API (since it's not yours, it belongs to a third party). See more here: https://github.com/testdouble/contributing-tests/wiki/Don%27t-mock-what-you-don%27t-own

For kicks, if you _really must_ do this, I would tighten it up:

```javascript
//subject

var someHandler = function (req, res) {
  return res.status(200).json('expected json');
}

//test

td = require('testdouble')
assert = require('assert')

var res = td.object(['status', 'json'])
td.when(res.status(200)).thenReturn(res)
td.when(res.json('expected json')).thenReturn('woot')

var result = someHandler(null, res)

assert.equal(result, 'woot')
```

This, of course, works, but it _overspecifies_ the subject's behavior by requiring `status` to be called before `json`. Here the fakes could be made to be more intelligent, but that would be useless complexity. Instead, I'd personally keep the express handler straightforward and imperative, have a minimum integration test that calls through it, and delegate to functions whose design I do own (where I could listen to my test pain and avoid chaining APIs like this)

**Comment by hbarcelos** [comment]
@searls the reason I'm doing this is because my code has branching, so I need to check if it will return the right status code for both valid and invalid cases. If the request is invalid I need to return a 4xx to the user.

I'm already stubbing out code that I do own, so the handler is pretty straightforward (15 lines top), but still needs some testing because of branching. Here is an example implementation:

```js
function getStates(req, res) {
  var countryList
  try {
    countryList = sanitizer(req.query.countries) // this is stubbed
  } catch (err) { // branching
    return res.status(400)
      .json({ error: err.message })
  }

  const stateList =  finder.findStates(geoData, countryList) // this is stubbed

  return res.json(stateList)
}
```

Do you really think it is necessary to create yet another layer to simplify this even more?

I could do something like:

```js
module.exports = function fetchStatesData(countryListAsJson) {
  var countryList
  try {
    countryList = sanitizer(req.query.countries) // this is stubbed
  } catch (err) { // branching
    return { status: 400, { body: { error: err.message } } }
  }

  const stateList =  finder.findStates(geoData, countryList) // this is stubbed

  return { status: 200, body: stateList }
}

//... somewhere else

function getStates(req, res) {
  const {status, body} = fetchStatesData(req.query.countries)
  return res.status(status)
    .json(body)
}
```

This way I could only test `fetchStatesData`'s return value and simply ignore `getStates`.

But is it worth it? What is the limit? Couldn't I end up with [Lasagna Code](http://wiki.c2.com/?LasagnaCode)?

---

Back to the issue, to me it seems like the message itself is kind of misleading:

Notice that I stub it like this:
```js
// This is a more generic expectation, as it would accept any Number
td.when(res.status(td.matchers.isA(Number)))
```

However, my verification is more explicit:
```js
// But I'm checking if the function has explicitly been called with 200
td.verify(res.status(200))
```

But look at the message:
> Warning: testdouble.js - td.verify - test double .status was both stubbed and verified with arguments (200)[...]

This is not what I did, I stubbed with `td.matchers.isA(number)`.

**Comment by searls** [comment]
> Do you really think it is necessary to create yet another layer to simplify this even more?

So one thing that I like to do is squeeze all branching out of "frameworkey" methods like this express handler, but it doesn't necessarily mean pushing all that branching down into my feature code (for instance, it'd be a shame to push down awareness of status codes into your domain logic, as that's exactly the sort of concern your http framework is dealing with).

So given your example:

```js
function getStates(req, res) {
  var countryList
  try {
    countryList = sanitizer(req.query.countries) // this is stubbed
  } catch (err) { // branching
    return res.status(400)
      .json({ error: err.message })
  }

  const stateList =  finder.findStates(geoData, countryList) // this is stubbed

  return res.json(stateList)
}
```

Here's how I would change the design in response to the testing pain you're experiencing:

```js
function jsonRoute (handler) {
  return function (req, res) {
    var result;
    try { 
      res.json(handler(sanitizer(req.query)))
    } catch (err) {
      res.status(400).json({error: err.message})
    }
  } 
}

app.use(jsonRoute(function (query) {
  return finder.findStates(geoData, query.countries)
})
```

So now your application feature handlers are truly imperative, and you have a conventional way for drawing routes (`jsonRoute`) that you can integration test separately as if it was a general purpose library or module and get it out of the line of fire of your feature testing. Additionally, it removes this try/catch flow control from the other N routes of your app, and gives you a single place to fix any changes (for instance, you might want to change that `400` to some other status code or complicate the error serving logic).

The takeaway here is whenever it feels like you need to mock something you don't own there is almost always another way to split the problem up such that you can avoid that pain. Trying to force it will either be painful at test-authoring time or code-changing time (when the test is tied up in knots, concerned with 3rd party API specifics).

**Comment by hbarcelos** [comment]
> [...] it'd be a shame to push down awareness of status codes into your domain logic [...]
Totally agreed (:

That's is the sort of thing that I would associate to Lasagna Code: so many layers that you will be forced to put some concerns into some part of the code that don't belong to it just for the sake of passing them around.

Your approach in deed seems cleaner and more manageable. I'll give it a try.

Thank's a lot.
