### ISSUE TITLE
Invoke callback within object

### ISSUE THREAD

**Issue by mattriley** [testdouble/testdouble.js#230]
Hi. Is it possible to invoke callbacks nested within an object? The following code doesn't seem to work:

`td.when(fileSystemService.exists({ filePath, onTrue: td.callback(), onFalse: td.matchers.isA(Function) })).thenResolve(true);`

**Comment by searls** [comment]
No, that is not supported currently, although it sounds like a worthwhile addition.

**Comment by searls** [comment]
Going to close, though, unless you plan on implementing
