### ISSUE TITLE
Mocha Spec Reporter

### ISSUE THREAD

**Issue by skbolton** [testdouble/testdouble.js#234]
I feel like this might be a little OCD but I have noticed something weird when using testdouble and mocha. I am going to put an excerpt of one of my tests.
```
before(() => { td.replace(console, 'log') })
after(() => { td.reset() })

it('should console.log the state of Model', () => {
      Opportunity
        .fields('.', 'child.name')
        .where({
          id: 5
        })

      Opportunity.explain()

      const callCount = td.explain(console.log).callCount
      expect(callCount).to.equal(1)
    })
```
The test passes but the spec reporter doesn't show one of the check marks
<img width="517" alt="screen shot 2017-04-29 at 5 55 04 pm" src="https://cloud.githubusercontent.com/assets/13260877/25559973/10330c72-2d05-11e7-91f6-dc6fb1630141.png">

I know things are technically working because if I change something in the test to make it break it does cause Mocha to fail.

<img width="654" alt="screen shot 2017-04-29 at 5 57 21 pm" src="https://cloud.githubusercontent.com/assets/13260877/25559987/54b19580-2d05-11e7-9bf3-67b6566c2fe9.png">

PS. For what it is worth I love your explain functionality of testdouble and I have a feature in the library I am creating that shows off the influence. 😄

**Comment by searls** [comment]
I suspect mocking console.log is not going to end well for you, since lots of other libraries (including Mocha) will call `console.log`. It's likely that's why you get two instead of 1.

I recommend wrapping console.log to your own logger and mocking that. See [this article](https://github.com/testdouble/contributing-tests/wiki/Don%27t-mock-what-you-don%27t-own). That's what we do in this lib [here](https://github.com/testdouble/testdouble.js/blob/master/src/log.js)

**Comment by skbolton** [comment]
I am totally with you and I just want to point out that I took a photo of that failed test to prove I can make the test fail. In the first photo the tests are 'passing' but no check marks are showing up in the reporter

**Comment by searls** [comment]
I'm sorry, I do not understand what your issue is

**Comment by skbolton** [comment]
<img width="518" alt="screen shot 2017-04-29 at 10 21 01 pm" src="https://cloud.githubusercontent.com/assets/13260877/25561466/2c223410-2d2a-11e7-96d0-1fa21057af8c.png">

To my earlier comment I will mock something other than console.log and see if I can get the same behavior. In the explain test suite I have 3 tests that use testdouble. They are all passing but not showing up in the reporter.

**Comment by searls** [comment]
Could you please provide a minimal example.

**Comment by skbolton** [comment]
Yeah I will make one and follow up if needed. Thanks for your time!
