### ISSUE TITLE
TypeScript: Better Generic Support for td.object()

### ISSUE THREAD

**Issue by sgtoj** [testdouble/testdouble.js#236]
Given the following... 

```
import * as td from "testdouble";

class FooBar {
  private _date: Date;
  constructor() {
    this._date = new Date();
  }
  public dateString() {
    return this._date.toString();
  }
}

let fooBarFake = td.object<FooBar>("FooBar" as any);
```

The above code will set `fooBarFake` to FooBar object as expected. TypeScript and `fooBarFake` behaves as I expect too. However, without `as any`, TypeScript will throw the following error...

`'"FooBar"' is not assignable to parameter of 'FooBar'`  

Take *notice* of the quote marks.  Without the generic parameter (`<FooBar>` ), TypeScript `fooBarFake` thinks it of `String` type.

I believe the parameter should not need to be cast as `any` type for the generic parameter to be accepted. 

```
import * as td from "testdouble";

// define FooBar class here

let fooBarFake = td.object<FooBar>("FooBar");
```

*As side note, I generally set TypeScript's `noImplicitAny` setting is to true.*

**Comment by searls** [comment]
I have no idea how to TypeScript. Would you send a PR?

**Comment by sgtoj** [comment]
I will look in to the source later (tonight afterwork?). I don't think the solution will be too difficult. Believe there only needs to be a small change to the way Proxy objects are created.

**Comment by searls** [comment]
Thanks! I met a few very nice people at NG Conf who offered to help make the typescript story for testdouble really shin

**Comment by searls** [comment]
Related, when you dig in there is a `test:typescript` script but I can't tell that it actually does anything. Any fix to that (or a new test that actually fails when broken) would be awesome

**Comment by sgtoj** [comment]
I have determined the caused TypeScript error is due to lodash's `.tap()` function -- [docs](https://lodash.com/docs/#tap). More specifically, I believe it's due to the function's interface definition defined in [@types/lodash](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/index.d.ts#L5946). Furthermore, it is working as designed: the explicit generic type parameter is suppose to match the first parameter's type.

I believe solution is creating a TypeScript definition for testdouble.js. Probably what the guys at the NG Conf were thinking too.

**Comment by searls** [comment]
Someone else has done this in an index.d.ts file in this repo already right?

**Comment by sgtoj** [comment]
You're right! Thanks! Overloading the `object()` function works too. I will push a PR soon.

**Comment by sgtoj** [comment]
Pull #237 submitted. As for your question about `test:typescript`, it does what it can because there is no real way to test `*.d.ts`. So that npm script runs the TS compiler against a `test.ts` script without generating a compiled script. If there were any *type* errors, the tsc throw them.
