### ISSUE TITLE
More support for ES Modules

### ISSUE THREAD

**Issue by kealthou** [testdouble/testdouble.js#246]
testdouble.js handles default export classes well, but can't handle default export functions, default export objects or named export objects.

```js
//func.js
export default function() {}
//test.js
const td = require("testdouble");
const func = td.replace("./func").default;
td.verify(func());
```
```
Error: Unsatisfied verification on test double `.default`.
```
If it produced the same result as when `module.exports` style was used like the below I'm happy.
```
Error: Unsatisfied verification on test double `./func`.
```
And,
```js
//object.js
export default {
    func() {}
}
export var named = {
    func() {}
}
//test.js
const td = require("testdouble");
const def = td.replace("./object").default;
const named = td.replace("./object").named;
console.log(def.func);
console.log(named.func);
```
Both def.func and named.func are not test doubles.

**Comment by searls** [comment]
Ok, we'll need to look into and investigate.

**Comment by Schoonology** [comment]
@kealthou I'm still looking into the latter case, but the former (replacing an `export default function`) is working as expected.

In your example you're calling `td.verify(someDouble())` without actually and previously invoking the double itself. Can you try the example below?

```js
//func.js
export default function() {}
//test.js
const td = require("testdouble");
const func = td.replace("./func").default;
func();
td.verify(func());
```

**Comment by kealthou** [comment]
@Schoonology I'm sorry if my point was unclear. Replacing a function with a test double itself is working well, but look at the error message, ``Error: Unsatisfied verification on test double `.default`.`` My point is about the name of the test double. It's `.default`. We don't have any idea what happened. On the other hand, ``Error: Unsatisfied verification on test double `./func`.`` is very easy to understand.

**Comment by searls** [comment]
I @kealthou I understand better your point now. For subordinate exports in a module, we should think about the test double naming.

Existing schemes:

* Replacing an object `td.replace(foo, 'bar')` will name its test double function of `baz` as `"bar.baz"`
* For constructor/classes, the above would be named `"bar#baz"`

So for cases like this with top-level exported functions, Something like `"./func.default"` wuoldn't be good, since that looks like a different filename. Any proposals?

**Comment by searls** [comment]
I believe the new and improved `td.imitate()` routine fixed this. Closing
