### ISSUE TITLE
Verify constructor

### ISSUE THREAD

**Issue by edenworky** [testdouble/testdouble.js#248]
`td#verify` does not seem to support the `new` operator. My use case is that I want to verify that a constructor is called with a specific argument. Is this possible?

**Comment by searls** [comment]
This works. Here's a demo: https://runkit.com/searls/verifying-constructor-calls

```js
var td = require('testdouble')

function Dog() {}
Dog.prototype.woof = function () {}

var FakeDog = td.constructor(Dog)

fakeDog = new FakeDog('bone')

td.verify(new FakeDog('chewtoy')) //<-- should blow up
```

**Comment by edenworky** [comment]
I see. In that case my issue is with `td#replace`. I saw the documentation for `td#constructor`, but I couldn't find any for this use case. I'm trying to replace a local module containing a class. I'm also using ES6 with Babel, so all my `require`s are `import`s, which means I'm always trying to replace `fooBar.default` instead of `fooBar`, and I want to spy on the constructor. Is this possible using TestDouble?

**Comment by searls** [comment]
Please provide an example project or runkit so I can see what you mean.
