### ISSUE TITLE
Is there any sample code that mock aws sdk?

### ISSUE THREAD

**Issue by johntangma** [testdouble/testdouble.js#251]

**Comment by searls** [comment]
Sorry, I lost track of this. No, we don't have such an example, but we'd encourage you to note that the lib is not designed to [fake out third-party API's](https://github.com/testdouble/contributing-tests/wiki/Don%27t-mock-what-you-don%27t-own) or [remote services](https://github.com/testdouble/testdouble.js/blob/master/docs/2-howto-purpose.md#test-doubles-and-unit-tests)
