### ISSUE TITLE
docs: simple page that lists the entire API

### ISSUE THREAD

**Issue by gurpreetatwal** [testdouble/testdouble.js#253]
I wasn't able to find document that lists/links to the library's complete API on a single page. The current docs are great for a quick getting started tutorial but aren't as helpful when you're using the library in a project already and don't remember the name or maybe the signature of one of the functions.

As an example, Sinon has [this page](http://sinonjs.org/releases/v2.3.2/).

**Comment by searls** [comment]
this is a good idea and overdue :+1:

**Comment by gurpreetatwal** [comment]
I can start working on this if you want; however I just started using the library yesterday :stuck_out_tongue_winking_eye: 

I was thinking of just adding a `API.md` to the docs folder, or maybe a wiki page?

**Comment by searls** [comment]
Since we haven't been using wiki yet it's probably not right to start now. I think an `docs/api.md` makes plenty of sense as a reference point, however, even if most of what it does is list out every top-level method and just link back to the workflow-organized markdown pages elsewhere

**Comment by gurpreetatwal** [comment]
Yeah I agree, the doc could have a "table of contents" which has the entire API and then each method in the doc would link to a section in the main docs.

Something like:
 
----
 
# API
...
 - [td.replace](likn)
....

# Methods
...
### td.replace(object, propertyName, [manualReplacement])  ⇒ fake
short description and link back to main docs
...

**Comment by searls** [comment]
yes, exactly

**Comment by gurpreetatwal** [comment]
Sounds good! I'll get started on this later today

**Comment by searls** [comment]
This is done if you look at the recently rewritten README.md
