### ISSUE TITLE
Verify that constructor is passed certain values

### ISSUE THREAD

**Issue by lastmjs** [testdouble/testdouble.js#256]
I would like to verify that a constructor was called with certain parameters, just like I would verify a function call. How can I do that? I was imagining something like:

```javascript
const MockConstructor = td.constructor(require('some-constructor'));

new MockConstructor({
  option1: true,
  option2: false
});

td.verify(new MockConstructor({
  option1: true,
  option2: false
}));
```

**Comment by searls** [comment]
Yes, and this works.

https://runkit.com/searls/testdouble-js-256
