### ISSUE TITLE
Building CoffeeScript at runtime is slow.

### ISSUE THREAD

**Issue by mweitzel** [testdouble/testdouble.js#29]
Its impact is roughly 200ms per runtime.

For a baseline, in a file `td-repro.js` I have
```
console.log('hi')
```
when ran, it gives the output
```
$ time node td-repro.js
hi

real	0m0.107s
user	0m0.083s
sys	0m0.016s
```

after an `npm install testdouble`, I replace the contents of `td-repro.js` with
```
var td = require('testdouble');
var myTestDouble = td.create();

myTestDouble('foo', 5)
td.verify(myTestDouble('foo', 5))
console.log('success')
```
and run again, with these results:
```
$ time node td-repro.js
success

real	0m0.369s
user	0m0.371s
sys	0m0.035s
```

But, if I
- comment out the first line of `index.js` (rather `node_modules/testdouble/index.js`)
- and execute `coffee -c node_modules/testdouble/lib/*.coffee node_modules/testdouble/lib/store/*.coffee~`

then the times are *way* down:
```
$ time node td-repro.js
success

real	0m0.190s
user	0m0.164s
sys	0m0.026s
```

From a baseline of ~110ms per run, a library that adds 70-80ms per run is incredible compared to one that adds 250ms.

**Comment by searls** [comment]
:+1:, I'd planned to switch to a prepublish step once the API settled down but having speed data makes it more urgent. 

Hey @jasonkarns, I'm sure you'd prefer to own how we configure this in the build? Ideas?

**Comment by jasonkarns** [comment]
mostly:

- prepublish to compile lib/.coffee to lib/.js
- npm ignores *.coffee
- git ignores *.js
- remove coffee registration from index.js
- add coffee registration to node-helper in tests
- test suite points directly to lib/.coffee and not index.js (probably
already does?)

**Comment by searls** [comment]
Sounds good. Would you like to take a stab at this and assign yourself or
no?
