### ISSUE TITLE
Update build workflow to deprecate GitHub dist folder, instead publish through a CDN

### ISSUE THREAD

**Issue by duluca** [testdouble/testdouble.js#290]
testdouble.js is transpiled, minified and gzipped for delivery. However, then the release artifact is committed to the GitHub repo. Following the separation of concerns principle, the repo should only contain the source artifacts that are used to make up the final product. Therefore, I would like to propose deprecating the dist folder version of testdouble.js and instead publish library through a CDN.

Further:
- It is a best practice for a CI/build pipeline to manage release artifacts,
- It is annoying to create a commit that is not-related to a documentation or source artifact change,
- Without a CDN non-npm users loose human readable version information. The instructions asks users to download the latest directly from GitHub -- `$ curl https://raw.githubusercontent.com/testdouble/testdouble.js/master/dist/testdouble.js -o test/helpers/testdouble.js`. At download time, the user has no idea what version they're getting.

Suggested implementation: 
Unpkg seems to be able to easily host npm packages that implement a umd folder. See https://unpkg.com for further details.

Implementation would be fairly easy:
- [ ] Add the umd (or dist) directory to your .gitignore file
- [ ] Add the umd directory to your files array in package.json
- [ ] Use a build script to generate your UMD build in the umd directory when you publish
- [ ] Update documentation with the new CDN url
- [ ] Add deprecation notice to current dist file for a period of 3-6 months, followed by removal

**Comment by jasonkarns** [comment]
Agree with this. long live `prepare` npm scripts!

And what timing! I _just_ published `packfiles`, a teeny cli utility to print a list of files that will be included in npm's tarball (so you don't need to `npm-pack` anything just to inspect the final tarball).

https://github.com/jasonkarns/packfiles
