### ISSUE TITLE
How to mock typescript fields

### ISSUE THREAD

**Issue by alexandru-calinoiu** [testdouble/testdouble.js#291]
I have the following typescript class:

```typescript
export class Fancy {
 public filed: string;
 
 public get otherField(): string {
 }
}
```

When I try to mock this 2 fields with `td.when(mock.field).thenReturn(something)` I get `testdouble.js - td.when - No test double invocation call detected for `when()``

I just want to mock `otherField` a readonly typescript property.

Can I mock typescript properties?

**Comment by searls** [comment]
test double does not support ES class properties, they must be invoked.

**Comment by alexandru-calinoiu** [comment]
Then invoke I will them.

**Comment by searls** [comment]
@davout1806 to my knowlede we haven't added anything that'd handle this
