### ISSUE TITLE
Node module mocking with td.replace()

### ISSUE THREAD

**Issue by andreventuravale** [testdouble/testdouble.js#294]
I want to know the formal behavior of **td.replace(modulePath: string)**.

Does it replace the module for every single request, or just on each call?

I'm asking this because I could not need have the real module for testing it in isolation when I needed. To be able to do that I did switch to td.constructor() to have a mocked type. Usually I run all test at once, some tests use X as a mocked dependency, and other use X as real dependency to test it in isolation, so if test runner runs tests that use td.replace() for X before X being tested for real, the last will fail because it will be a mocked version.

Just wondering if it is the expected behavior and should be as is, I mean by design, or if it is something that could is opened for discussion.

Regards,
André

**Comment by searls** [comment]
Sorry, I don't understand your question. Could you please provide an example.

For how it works, check out the quibble library: https://github.com/testdouble/quibble

**Comment by searls** [comment]
To be clear, I don't understand where you have an issue. So long as `td.reset()` is run after each test, you of course can replace a dependency in some tests and test it directly in others.

**Comment by andreventuravale** [comment]
Got it, I just needed to know the right way to do it, so I will make use of reset() after my tests.

Thanks.

**Comment by searls** [comment]
Cool. Happy testing!
