### ISSUE TITLE
Error when running install inside testdouble.js

### ISSUE THREAD

**Issue by jasonkarns** [testdouble/testdouble.js#298]
A fresh yarn install within testdouble package flows up with a node-gyp error:

<details>
<summary>$ yarn</summary>
<pre><code>
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
error /Users/jasonkarns/Projects/td/testdouble.js/node_modules/deasync: Command failed.
Exit code: 1
Command: node ./build.js
Arguments: 
Directory: /Users/jasonkarns/Projects/td/testdouble.js/node_modules/deasync
Output:
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:655:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
warning Error running install script for optional dependency: "/Users/jasonkarns/Projects/td/testdouble.js/node_modules/fsevents: Command failed.\nExit code: 1\nCommand: node install\nArguments: \nDirectory: /Users/jasonkarns/Projects/td/testdouble.js/node_modules/fsevents\nOutput:\nnode-pre-gyp info it worked if it ends with ok\nnode-pre-gyp info using node-pre-gyp@0.6.33\nnode-pre-gyp info using node@8.8.1 | darwin | x64\nnode-pre-gyp info check checked for \"/Users/jasonkarns/Projects/td/testdouble.js/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node\" (not found)\nnode-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz\nnode-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz\nnode-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz \nnode-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.1 and node@8.8.1 (node-v57 ABI) (falling back to source compile with node-gyp) \nnode-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)\nnode-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jasonkarns/Projects/td/testdouble.js/node_modules/node-pre-gyp/lib/util/compile.js:77:29)\nnode-pre-gyp ERR! stack     at emitOne (events.js:115:13)\nnode-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:7)\nnode-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)\nnode-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:374:16)\nnode-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)\nnode-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:180:9)\nnode-pre-gyp ERR! System Darwin 16.7.0\nnode-pre-gyp ERR! command \"/usr/local/Cellar/node/8.8.1/bin/node\" \"/Users/jasonkarns/Projects/td/testdouble.js/node_modules/fsevents/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"\nnode-pre-gyp ERR! cwd /Users/jasonkarns/Projects/td/testdouble.js/node_modules/fsevents\nnode-pre-gyp ERR! node -v v8.8.1\nnode-pre-gyp ERR! node-pre-gyp -v v0.6.33\nnode-pre-gyp ERR! not ok \nFailed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)"
info This module is OPTIONAL, you can safely ignore this error
</code></pre>
</details>

yarn: 1.3.2
node: 8.8.1

**Comment by searls** [comment]
any insight into what's going on?

**Comment by jasonkarns** [comment]
not yet, wanted to throw this out there in case anyone else encounters. planning on digging some tomorrow.

**Comment by jasonkarns** [comment]
I'm assuming it's an issue with node-gyp.

It works fine on all versions of node that have an npm higher than 5.3. It failed on my brew-installed node 8.9.1, but succeeded on nodenv's 8.9.1. The only difference between them is how homebrew manages its version of npm separately. And since npm manages its version of node-gyp separately, I'm just assuming they're related.

So if anyone else has this issue, recommended workaround: don't use homebrew's node. Use a nodenv-installed node (+ a recentish version of npm so that you have recentish node-gyp).

Or if you really like homebrew's node/npm/node-gyp, maybe do the force upgrade documented here: https://github.com/nodejs/node-gyp/wiki/Updating-npm's-bundled-node-gyp (I did not try this because: 💚  <img src="https://user-images.githubusercontent.com/119972/32970953-2110f51a-cbb9-11e7-92f8-f2f56958ae7c.png" height="28" style="vertical-align: middle;" />
