### ISSUE TITLE
Use testdouble.github.io for docs

### ISSUE THREAD

**Issue by nomorepanic** [testdouble/testdouble.js#313]
Currently the docs are quite hard to search through, because they lack a proper navigation menu in each page, it's only in the README.md.

Since you are using markdown for docs and are already on github, I believe it should be fairly easy to set up Github Pages with testdocs. 

This would improve the readability and ease of use the documentation

**Comment by searls** [comment]
Yeah, agree. Been meaning to get around to adding a git-book build that we can absorb as a sub-site of testdouble.com, just got stalled last time futzing with the look of it

**Comment by giltayar** [comment]
Stale. Closing. Please reopen if still relevant and I will look into it.
