### ISSUE TITLE
td.explain could explain the state of captors a bit

### ISSUE THREAD

**Issue by jasonkarns** [testdouble/testdouble.js#315]
This _may_ not be all that valuable, since captors are nearly a plain object anyway. But it would be nice to have a helpful descriptive output for captors that showed info about their state.

**Comment by searls** [comment]
I believe this can be accomplished by setting a function to the `name` attribute. See [isA](https://github.com/testdouble/testdouble.js/blob/master/src/matchers/builtin/is-a.js#L6-L8).

Should be a simple patch to captor [here](https://github.com/testdouble/testdouble.js/blob/master/src/matchers/builtin/captor.js#L6)

**Comment by giltayar** [comment]
Stale. Closing. Please reopen if still relevant and I will look into it.
