### ISSUE TITLE
td.replace - support lerna wherein sub-modules replace one other

### ISSUE THREAD

**Issue by searls** [testdouble/testdouble.js#326]
See #324 for more details, specifically to support [this case](https://github.com/arelra/testdouble-issue-324-symlink-module-regression), in which a user runs tests from the top-level directory. AFAICT, any references to "symlinks" are a red herring, the real issue has to do with the fact lerna isn't careful about setting current working directory:

The root issue appears to be that `td.replace` will depend on `process.cwd()` for determining which path to use as the base for any `resolve()` lookups, but lerna apparently does not change the current working directory as it runs each sub-module's `test` script. As a result, any tools that depend on the current working directory being that of the project itself will behave inconsistently, as we're seeing with `td.replace()` in this case.

A workaround for now would be for each submodule's test suite to set up "before all" and "after all" hooks which `process.chdir()` to their project root and then back to whatever it had been set previously. The referenced repo's test could be fixed by doing this, to illustrate:

```js
// Before All
var cwd = process.cwd()
process.chdir(__dirname)

// Test
var td = require('testdouble');
var assert = require('assert')

var symlinkedThing = td.replace('package-a')
var subject = require('./index')
td.when(symlinkedThing()).thenReturn('fake thing')

assert.equal(subject(), 'fake thing')

// After All
process.chdir(cwd)
```

**Comment by giltayar** [comment]
Stale. Closing. Please reopen if still relevant and I will look into it.
