### ISSUE TITLE
td.replace a required method?

### ISSUE THREAD

**Issue by jlmangh** [testdouble/testdouble.js#353]
Maybe I'm missing this in the documentation, but how do you `td.replace()` a required function in node.js so that you can verify it was called (and called with the correct parameters)?  I'm not trying to test that it has the correct output - the required module has its own tests.  Just simply trying to test if it was called correctly or not.

eg given that I have a module I wrote: `doDomethingCool.coffee`

```
module.exports = (i) ->
  return i**
```

Now I do already have tests with 100% coverage of this module, so I'm happy it works.

But in my next module, that requires `doSomethingCool`, how do I td.replace the requirement?

The other module, `doSomethingBoring.coffee`

```
doSomethingCool = require "./doSomething"
module.exports = (i) ->
    # log the required func so we can see if it has been td.replaced or not
    console.log doSomethingCool.toString()
    i = i++
    return doSomethingCool(i)
```

And the test  `test_doSomethingBoring.coffee`:

```
td = require "testdouble"
doSomethingBoring = require "./doSomethingBoring"
describe 'do something boring module', ->
    it 'calls doSomethingInteresting with the correct parameters, ->
        doSomethingInteresting = td.replace "./doSomethingInteresting"
        doSomethingBoring(1)
        td.verify(doSomethingInteresting(2))
```

But the test fails with `Error: Unsatisfied verification on test double`, and the console.log statement shows the original function was called, not the testdouble function.

Is this possible to achieve?

**Comment by searls** [comment]
Sorry for how long it took to respond to this issue, but the `td.replace` module-replacement mechanism works by monkey-patching the module loader at runtime, which means you have to specify replacements before you require the subject under test.

So I'd take your example and the first thing I'd try is:

```js
td = require "testdouble"
describe 'do something boring module', ->
    it 'calls doSomethingInteresting with the correct parameters, ->
        doSomethingInteresting = td.replace "./doSomethingInteresting"
        doSomethingBoring = require "./doSomethingBoring"

        doSomethingBoring(1)

        td.verify(doSomethingInteresting(2))
```
