### ISSUE TITLE
Critical dependency: the request of a dependency is an expression?

### ISSUE THREAD

**Issue by chris-dura** [testdouble/testdouble.js#354]
### Description

Just run the tests that were working just fine on previous versions.

### Issue

Upgrading from `v3.2.6` to `v3.5.2` now pumps out a warning with Webpack/Karma/Mocha...

```
WARNING in ./node_modules/testdouble/lib/replace/module.js
29:15-54 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/testdouble/lib/replace/module.js
 @ ./node_modules/testdouble/lib/replace/index.js
 @ ./node_modules/testdouble/lib/index.js
 @ ./test/unit/my-tests/my.test.js
 @ ./test/unit \.test\.js$
 @ ./test/unit/index.js

WARNING in ./node_modules/testdouble/lib/replace/module.js
33:15-35:17 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/testdouble/lib/replace/module.js
 @ ./node_modules/testdouble/lib/replace/index.js
 @ ./node_modules/testdouble/lib/index.js
 @ ./test/unit/my-tests/my.test.js
 @ ./test/unit \.test\.js$
 @ ./test/unit/index.js
```

### Environment

- [x] `node -v` output: `v8.9.4`
- [x] `npm -v` (or `yarn --version`) output: `5.7.1`
- [x] `npm ls testdouble` (or `yarn list testdouble`) version: `testdouble@3.5.2`

#### Code-fenced Examples

```js
import td from 'testdouble';

describe('Some Test', function() {
  it('tests testdouble', () => {
    const foo = td.func('bar');
    assert.isOk(true);
  });
});
```

**Comment by tyler36** [comment]
Same for me after updating

**Comment by searls** [comment]
Could you please provide a minimal repo that reproduces this issue? That'd help me figure out the exact cause

**Comment by tyler36** [comment]
Sorry for the late reply.

https://github.com/tyler36/testdouble-warning

OS: Win10
node -v: 9.4.0
yarn --version: 1.5.1
testdouble@3.6.0

**Comment by searls** [comment]
I think I have this fixed by adding both `src` and `lib` for that file to the package.json's `browser` directive

**Comment by chris-dura** [comment]
@searls Can you clarify, I don't quite understand what you're referencing?

**Comment by searls** [comment]
This fixes it: https://github.com/testdouble/testdouble.js/blob/master/package.json#L56

I can't cut a release until we overcome various npm related issues locally though

**Comment by chris-dura** [comment]
ah ok, thank you!

**Comment by ZarekParker** [comment]
@searls seeing this on 3.8.1

```
Warning in ./node_modules/testdouble/lib/replace/module/require-actual.js

  Critical dependency: the request of a dependency is an expression

Warning in ./node_modules/testdouble/lib/replace/module/require-actual.js

  Critical dependency: the request of a dependency is an expression
```
