### ISSUE TITLE
Compare dates when using td.matchers.contains

### ISSUE THREAD

**Issue by bjarketrux** [testdouble/testdouble.js#358]
### Description
Testdouble.js does not seem to compare dates when using td.matchers.contains

### Issue
Given the following code:
```javascript
const td = require('testdouble')
const mock = td.func()

function run() {
    mock({ date: new Date("2001") });
}

run();

const arg = td.matchers.contains({ date: new Date("2005") });
td.verify(mock(arg));
```

I expect the test to fail (dates are not the same), but the test passes:
https://runkit.com/bjarketrux/testdouble-js-matchers-contains-date/1.0.0

If I do not use contains then the test fails as expected:
https://runkit.com/bjarketrux/testdouble-js-matchers-contains-date/1.1.0

### Environment
node 8.10.0
testdouble 3.5.2

**Comment by searls** [comment]
Good catch, totally legit bug, pain in the ass to fix. Landed in testdouble@3.7.0
