### ISSUE TITLE
Remove es6-map polyfill

### ISSUE THREAD

**Issue by searls** [testdouble/testdouble.js#367]
It looks like es6-map is now supported sufficiently on all evergreen browsers and supported Node versions, so we ought to be able to safely remove our es6-map dependency

http://kangax.github.io/compat-table/es6/#test-Map

**Comment by primarilysnark** [comment]
This is now resolved by #405.

**Comment by searls** [comment]
You probably know this, but an FYI in case not -- if you had written "Fixes #367" (or "Resolves") into the body of the PR it'd have auto closed this issue
