### ISSUE TITLE
Awaiting a testdouble function always resolves

### ISSUE THREAD

**Issue by lumaxis** [testdouble/testdouble.js#371]
### Description

I'm trying to verify a function that calls several APIs but otherwise produces no output. I'm passing in the API client objects as parameters so they are easily replaceable with testdoubles.

### Issue

When using `async/await` and awaiting any testdouble function, the function always returns undefined which makes the code continue. I would have expected the function to only ever resolve if I explicitly set that up with `td.when(…).thenResolve()`.

Is this intentional behavior and is there already a proposed way to solve my use case? The only workaround I can think of right now is explicitly throwing an error when my testdouble is called with the wrong parameters.

### Environment

- [x] `node -v` output: 8.9.4
- [x] `npm -v` (or `yarn --version`) output: 6.0.0
- [x] `npm ls testdouble` (or `yarn list testdouble`) version:

#### Code-fenced Examples

```js
const td = require('testdouble');

const func = async () => {
  await td.function('my func')();

  console.error('This should never be reached')
}

func();
```

**Comment by searls** [comment]
By default, `td.func()()` will return `undefined`, not an unfulfilled promise, so I don't think there'd be anything to await there. (I haven't used async/await much yet, so I don't know what happens when the thing to the right of await doesn't evaluate to a promise.)

You might try this:

```js
const lol = td.when(td.func()).thenReturn(new Promise())

await lol()
```

??

**Comment by neall** [comment]
To answer Justin's implied question, from the [MDN page on await][await]:
> If the value of the expression following the await operator is not a Promise, it's converted to a resolved Promise.

[await]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#Description

That's why the default behavior of `td.func()()` returning `undefined` is the same when you `await` as if it had returned a promise resolved with `undefined`.

So if you want the result of the function to resolve with a value other than `undefined`, you can do:

**Comment by searls** [comment]
Closing in favor of #372
