### ISSUE TITLE
How to replace momentjs ?

### ISSUE THREAD

**Issue by packlikez** [testdouble/testdouble.js#378]
I can't replace momentjs dependency help me. Thanks.

**Comment by searls** [comment]
Assuming you mean you're trying to literally mock out moment.js using `td.replace('moment')`, then we wouldn't recommend or support that. Some details on why here: https://github.com/testdouble/contributing-tests/wiki/Don't-mock-what-you-don't-own

**Comment by packlikez** [comment]
Can you give me a example to replace moment ?
