### ISSUE TITLE
Getting a not a constructor error when trying to stub an external class dependency

### ISSUE THREAD

**Issue by mattallenuk** [testdouble/testdouble.js#382]
### Description
I'm trying to stub a dependency of the module I'm testing.

### Issue

I'm new to using TestDouble so this is likely just my ignorance. I am trying, unsuccessfully so far, to stub a dependency of a module under test. The dependency is a module containing a class declared using module.exports = class clsName style. I can get a stubbed version but in my module when new clsName is executed it comes back with an error saying clsName is not a constructor. 

I'm actually using Typescript but the code below is a contrived example of what I'm trying to do in plain Javascript. Is there anything obvious that I am doing wrong? Can I do what I'm attempting to do?

### Environment

node 10.5.0
npm 6.3.0
testdouble 3.8.1
mocha 5.2.0

#### Code-fenced Examples

dep.js
```js
module.exports = class DependencyA {
    constructor(options) {
        this.options = options;
    }
    doSomething(){
        return 'DidSomething';
    }
}
```

undertest.js
```js
const DependencyA = require('./dep');
export class UnderTest {
   constructor() {
       this.depA = new DependencyA({anOption: 12});
   }
   doIt() {
       return this.depA.doSomething();
   }
}
```

test.js
```js
const td = require('testdouble');
describe('UnderTest', () => {
    let UnderTest = null;
    beforeEach(() => {
        const DependencyA = td.replace('./dep');
        td.when(new DependencyA(td.matchers.anything())).thenReturn({});
        td.when(DependencyA.prototype.doSomething()).thenReturn('I did it!');
        UnderTest = require('./undertest').UnderTest;
    });

    afterEach(() => {
        UnderTest = null;
        td.reset();
    });
    
    it('Can Be Created', () => {
       const underTest = new UnderTest();
    });
});
```

**Comment by mattallenuk** [comment]
Have managed to sort this out. Was not including the Dep.js file correctly in my Typescript code.

**Comment by searls** [comment]
Sorry that I took so long to respond to you that you had to solve this entirely alone. I'll try to be more responsive!

**Comment by mattallenuk** [comment]
Not a problem at all! Thanks @searls.
