### ISSUE TITLE
Fake timers / mock Date

### ISSUE THREAD

**Issue by sarneeh** [testdouble/testdouble.js#383]
Quick question: can I somehow use `testdouble` to mock out `Date`? I mean a similiar functionality to [sinon fake timers](https://sinonjs.org/releases/v6.3.4/fake-timers/). I tried few approaches with `td` but it didn't work out 😢

**Comment by rosston** [comment]
I can’t speak to precisely why `testdouble` _can’t_ do what you’re trying to do.

But if you haven’t looked at it before, I might suggest looking at the contributing-tests wiki, specifically [“Don’t mock what you don’t own”](
https://github.com/testdouble/contributing-tests/wiki/Don%27t-mock-what-you-don%27t-own). That whole page is worth reading for the background (and it’s not very long), but the last section suggests a way forward: putting your use of `Date` in your own wrapper, which you can then design for easy use/mocking.

**Comment by sarneeh** [comment]
@rosston That makes sense. I always forget about this rule, but it really makes sense 😄 Thanks!
