### ISSUE TITLE
How do I verify only 1 of 2 stubbed functions was called?

### ISSUE THREAD

**Issue by boblauer** [testdouble/testdouble.js#384]
### Description
I have a class with a `create` and `update` method, and I want to verify the correct one is called in certain scenarios.

### Issue

Both `create` and `update` methods are stubbed functions. Neither has a return value. In my test, I am using `td.verify(client.create())`. This works, but it gives the warning about using `td.when` and `td.verify` together.

Is there a better way to verify that `client.create` has been called and `client.update` has not?

**Comment by searls** [comment]
Hi @boblauer.

here's a demo script that demonstrates what you are asking:

```js
const td = require('testdouble')

const app = {
  client: {
    create () {},
    update () {}
  }
}

const subject = () => {
  app.client.create('lol')
}

// Imagined test code
td.replace(app, 'client')

subject()

td.verify(app.client.create('lol'))
td.verify(app.client.update(), {times: 0, ignoreExtraArgs: true})

// Alternatively you can just make sure it wasn't called by inspecting it:
require('assert').equal(td.explain(app.client.update).callCount, 0)

// Don't forget to have reset called in an afterEach hook somewhere
td.reset()
```

Relevant [docs here](https://github.com/testdouble/testdouble.js/blob/master/docs/6-verifying-invocations.md#configuring-verifications)
