### ISSUE TITLE
td.replace before it vs td.replace inside of it

### ISSUE THREAD

**Issue by nohaibogdan1** [testdouble/testdouble.js#394]
When I call td.replace(module) outside of it (inside of a describe) node  gives this error.
 `Error: testdouble.js - td.replace - No "undefined" property was found.`

The error  goes away if I do `td.replace(module, 'property')`

But inside of it td.replace(module) will work.

**Comment by searls** [comment]
`td.replace` should only be used in the context of running a test, so inside an `it` or `beforeEach`, but not inside a `describe` callback (which is suite-definition time, not test-run-time) or at the top of a module (which is module-load-time). See the example in the [docs](
https://github.com/testdouble/testdouble.js/blob/master/docs/7-replacing-dependencies.md#nodejs)
