### ISSUE TITLE
td.replace a double arrow function

### ISSUE THREAD

**Issue by EduardoGarciaM** [testdouble/testdouble.js#411]
### Description

I'm not sure if it's not supported or it's my fault but basically this is a oversimplification of my function:

```java
const doStuffs = (valueA) => async (valueB, valueC) {
    const result = valueA + valueB + valueC
    return result
}

module.exports = {
    doStuffs,
}
```

where i use the function:

```javascript
const example = require(./doStuffs)

const whatEver = example.doStuffs(1)(2, 3)
```

the test:

```javascript
const example = require(./doStuffs)
const functionToTest = require(./path)

td.replace(example, 'doStuffs')
td.when(example.doStuffs(1)(2, 3).thenReturn(6)
```

error:
`example.doStuffs(...) is not a function`

**Comment by searls** [comment]
Sorry, but this example isn't valid JS so I don't really understand what you're describing. Can you please provide a working example and we'll reopen it?
