### ISSUE TITLE
How to stub out instance methods and replace dependencies  when writing a request test?

### ISSUE THREAD

**Issue by robskrob** [testdouble/testdouble.js#414]
### Description
I have an [endpoint I want](https://github.com/robskrob/routes-test-api-td/blob/master/index.js#L39) to test which involves stubbing out an [API call](https://github.com/robskrob/routes-test-api-td/blob/master/models/return_order.js#L17).

In my test I am [trying to stub](https://github.com/robskrob/routes-test-api-td/blob/master/test/routes/index.js#L19) it out with `td.when`.

High level I guess one could say I'm trying to write an integration test while only stubbing out the API calls. I'm trying to create coverage of my app as I would with a [request test](https://relishapp.com/rspec/rspec-rails/docs/request-specs/request-spec) in Rails.

I'm using `mocha` to run my tests and `chai` for expectations. 

Please note that the above links are to a sample app. 

### Issue

How can I stub out the instance method `OrderResource#getOrder` to return an `order` instance so that my API test does not make an HTTP API call? The only API call I want it to make is the one that hits `localhost:8080`, which is running my application.

This [stub](https://github.com/robskrob/routes-test-api-td/blob/master/test/routes/index.js#L19-L24) is not successfully stubbing out the method that implements an api call: `await this.orderResource.getOrder(this.getOrderNumber())`.

I tried to substitute out the [`OrderResource` dependency](https://github.com/robskrob/routes-test-api-td/blob/master/test/routes/index.js#L11) and create a double based on this replacement, but for some reason `OrderResource#getOrder` continues to execute.

I've watched your [very informative video](http://blog.testdouble.com/posts/2016-06-05-happier-tdd-with-testdouble-js) -- thank you for this video by the way -- and I have also read the documentation on [replacing real dependencies](https://github.com/testdouble/testdouble.js/blob/master/docs/7-replacing-dependencies.md), but I cannot seem to either successfully replace the `OrderResource` or stub `OrderResource#getOrder`. 

I have noticed that a lot of your documentation / examples do not include JavaScript Classes. I am using JS classes so maybe that's the issue. I am not too sure how I should use your library differently when handling classes and their corresponding instances. 

I was hoping I could stub out my running instances as you demonstrate here with [constructor functions](https://github.com/testdouble/testdouble.js/blob/master/docs/4-creating-test-doubles.md#tdconstructor):
```js
td.when(FakeDog.prototype.bark()).thenReturn('YIP')

var dog = new FakeDog()

dog.bark() // 'YIP
```

**Comment by searls** [comment]
I think before diving in and trying to debug the particulars as to what's not working here (and I'm sure that's solvable), I'd first suggest using a different tool than a mocking library for faking out an external dependency like an API call. 

For that purpose, I think the best tool right now is [nock](https://github.com/nock/nock). (We have [testdouble-nock](https://github.com/testdouble/testdouble-nock) as a wrapper, too, but it's pretty bare bones right now)

Reason being is that the purpose of a test like this is probably to make sure the system is working when all the units are plugged together _except for_ some external integration. If that's the case, then I would want to protect the veracity of the code under test by not poking any holes in implementation details like particular objects and functions. Instead, I'd keep the code under test sacrosanct and instead fake out the networking by providing stubs of the network responses. (Related: this talk covers that at greater length: https://blog.testdouble.com/posts/2018-03-06-please-dont-mock-me )

**Comment by robskrob** [comment]
@searls thank you for the response. I will check out your talk.
