### ISSUE TITLE
td.matchers.contains has missing splat type in TypeScript

### ISSUE THREAD

**Issue by sukima** [testdouble/testdouble.js#415]
### Description
Per the [documentation](https://github.com/testdouble/testdouble.js/blob/7b222aeef090678eb3a6054675c69a1391387b7b/docs/5-stubbing-results.md#arrays) and the [tests](https://github.com/testdouble/testdouble.js/blob/ca452500f036e03b1e00c56f1983fec4bcaab78c/test/safe/matchers.test.js#L116) the `td.matchers.contains()` can take multiple arguments. However, the [type definitions](https://github.com/testdouble/testdouble.js/blob/7b222aeef090678eb3a6054675c69a1391387b7b/index.d.ts#L38) do not account for this.

### Issue

If you attempt to compile the following:

```ts
td.matchers.contains('a', 'b', 'c');
```

TypeScript will complain:

```
Expected 1 arguments, but got 3.
```

**NOTE** That both the tests and the documentation claim otherwise.

### Environment

- [x] `node -v` output: `v10.15.3`
- [x] `npm -v` (or `yarn --version`) output: `6.4.1`
- [x] `npm ls testdouble` (or `yarn list testdouble`) version: `testdouble@3.11.0`

### Failing Test

TypeScript is not testable in the current code base.

### Example Repo

```
git clone https://gist.github.com/73a9cd328d038e9c81ee8dee21e7b499.git
```

**Comment by searls** [comment]
Great catch! I'm not using TypeScript so I tend to rely on folks like you to keep the typings file we publish accurate and up to date. Please send a PR!

**Comment by sukima** [comment]
> Please send a PR!

I wish I could. My TypeScript-fu goes as far as being able tell there is a problem and that is it. To be honest life was a lot easier in JavaScript land. But other swear by TS; I don't know. Anyway I don't rightly know how to handle splat args.

If I do discover how to do that I will promptly make a PR. Till then, I'll just have to work around things. Sorry *(sheepish smile)*

**Comment by richrout** [comment]
Just encountered this problem. Fixed it with a local definition: 
```
declare module 'testdouble' {
  interface Matchers {
    contains(...args: any[]): any;
  }
}
```

Just changing the `matchers.contains` definition to that should be sufficient.

**Comment by giltayar** [comment]
Stale. Closing. Please reopen if still relevant and I will look into it.
