### ISSUE TITLE
ReferenceError: td is not defined 

### ISSUE THREAD

**Issue by AzranAzwer** [testdouble/testdouble.js#418]
I have started the unit testing for login redux part, i found an article about writing testing including td when i save my test case i got an error "ReferenceError: td is not defined"

please help to how to import td.function("xxx") without error

**Comment by searls** [comment]
I'm sorry, I don't really know what you're referring to, and without an example or link I don't think we'll be able to help you.

Using Node's default module system, you can just `cont td = require('td')` and then reference `td.function()` so long as it's installed
