### ISSUE TITLE
td.object() cannot be used as an argument inside td.when(...)

### ISSUE THREAD

**Issue by gnicolae14** [testdouble/testdouble.js#419]
### Description

I am trying to mock the return value of a function that accepts an argument.

### Issue

I cannot mock the return value of a function with an argument when using td.object() as the argument.

E.g.
```js
arg = td.object();
td.when(mocked(arg)).thenReturn('mocked');
mocked(arg) --> returns undefined
```

The issue only appears when `arg = td.object()`. The code is successfully executed when using a generic object like `arg = {}` or `arg = "some-string"`

### Environment

- [ ] `node -v` output: v8.15.0
- [ ] `npm -v` (or `yarn --version`) output: 6.9.0
- [ ] `npm ls testdouble` (or `yarn list testdouble`) version: testdouble@3.12.0

#### Code-fenced Examples

The following example showcases the issue:

```js
const td = require('testdouble');

function check(desc, arg) {
  const mocked = td.function();
  td.when(mocked(arg)).thenReturn('mocked');
  console.log(desc, '::', mocked(arg), ':: match:', mocked(arg) === 'mocked');
}

check('{}', {});
check('"string"', 'string');
check('td.object()', td.object());
```

The output of executing the example:
```
{} :: mocked :: match: true
"string" :: mocked :: match: true
td.object() :: undefined :: match: false
```

**Comment by searls** [comment]
I just tried to verify this on master running `script/repl` and failed. Although I would strongly urge folks in most cases to avoid passing a mock to a mock or returning a mock from a mock, this seems to work fine:

```js
td > const fake1 = td.func('fake1')
undefined
td > const fake2 = td.func('fake2')
undefined
td > td.when(fake1(fake2)).thenReturn('sweet')
{ [Function: testDouble] toString: [Function] }
td > fake1(fake2)
'sweet'
```

**Comment by gnicolae14** [comment]
@searls It does work for me as well with `fake2 = td.func()` but it still fails for `fake2 = td.object()`

**Comment by searls** [comment]
Whoops, I'll take a second look tomorrow

**Comment by gnicolae14** [comment]
Thanks.

My initial investigation was pointing that td.object() was being identified as a matcher and the match was failing (fake object had `__matches` property defined).

This might have something to do with properties being automatically added to fake objects (which might be a feature or implementation detail I am not aware of).

Tested with `scripts/repl` on master:

```js
td > fake = td.object()
undefined
td > Object.getOwnPropertyNames(fake)
[ 'toString', 'constructor', 'length' ]
td > fake && fake.__matches && fake.__properties_just_appear_like_magic
undefined
td > Object.getOwnPropertyNames(fake)
[ 'toString',
  'constructor',
  'length',
  '__matches',
  '__properties_just_appear_like_magic' ]
```

**Comment by noah-potter** [comment]
Any progress on this? I'm running into this and I have a more complex use case that I could use some guidance on.

Here's the example repo based on CRA: https://github.com/noah-potter/testdouble-example-1
See `/src/App.test.tsx` for the test.

To explain this further, see line 18 where the builder uses chained methods. In my real project, this is the 3rd party library SignalR doing something like `const connection = new HubConnectionBuilder().withUrl(...).withAutomaticReconnect().build()` and then I'm doing something with the resulting connection, like listening for events on the connection.
So the path I'm heading down is trying to provide mocks for the return of each mock throughout that chain so it'll compile. However, I'm running into this issue where mocked objects don't pass matchers.

I can simply keep using `.argThat`, but it feels like a hack. Or maybe there's a restructure in here that I'm missing that'll make nested mocks unnecessary.
