### ISSUE TITLE
Security vulnerability: testdouble uses a vulnerable version of lodash

### ISSUE THREAD

**Issue by michdsouza** [testdouble/testdouble.js#428]
### Description

testdouble uses a vulnerable version of lodash, see https://www.npmjs.com/advisories/1065 for more details on the security issue. lodash >=4.17.12 is patched.

### Issue

| high          | Prototype Pollution                                                       |   
|---------------|---------------------------------------------------------------------------|
| Package       | lodash                                                                    |
| Patched in    | >=4.17.12                                                                 |
| Dependency of | testdouble                                                                |
| Path          | testdouble > lodash                                                       |
| More info     | https://www.npmjs.com/advisories/1065                                     |
### Environment

- [ ] `node -v` output:
- [ ] `npm -v` (or `yarn --version`) output:
- [x] `npm ls testdouble` (or `yarn list testdouble`) version: 3.8.1

**Comment by searls** [comment]
Landed in 3.12.4
