### ISSUE TITLE
Feature request: fail when stub called with arguments not maching any configured call.

### ISSUE THREAD

**Issue by pasku** [testdouble/testdouble.js#429]
Currently, when I call an object stub instance (one created with `td.object<MyTypescriptClass>()`) passing arguments which do not match any previously configured call, that call returns undefined. It would be very useful if such a call would throw an error such as `UnexpectedStubCall` with details about the arguments mismatch.

This would be a breaking change, so it would probably need to be configured or used through a slightly different API.

What do you think about this?

**Comment by searls** [comment]
What you're describing is (in short), a difference between a mock and a spy. Test Double's fakes serve as stubs—providing a pre-configured response to certain inputs—and as spies—recording and telling you after-the-fact what they were called with.

[Mocking](https://github.com/testdouble/contributing-tests/wiki/Mock) libraries, on the other hand, produce fakes that do both at once, in that every single interaction must be specified in advance of the call to the subject, which forces them to break [arrange-act-assert](https://github.com/testdouble/contributing-tests/wiki/Arrange-Act-Assert) order. Additionally, it tends to lead to _overspecified_ tests where tests default to enforcing with too little flexibility how a particular thing ought to be called as opposed to the minimum needed to satisfy the contract between the subject and the dependency.

For these reasons, testdouble.js does not provide the behavior associated with traditional mock objects.
