### ISSUE TITLE
Is there a way to reset the state of a double?

### ISSUE THREAD

**Issue by BrianGenisio** [testdouble/testdouble.js#43]
I'm in need of something like:

```javascript
td.clear(theDouble);
```

I'd love to just create a double every test, but I am using [proxyquire](https://github.com/thlorenz/proxyquire) to to inject "import" doubles which means I get one shot at creating a double option.  Now the state of the double gets accumulated, which is not ideal.

**Comment by searls** [comment]
`td.reset()`

**Comment by searls** [comment]
I'd recommend sticking that in an `afterEach` for every test to avoid pollution

**Comment by BrianGenisio** [comment]
Nice.  I even looked at the code and passed right over it.  Thanks.

That should be in the Readme: https://github.com/testdouble/testdouble.js/pull/44
