### ISSUE TITLE
Testing Extended Class

### ISSUE THREAD

**Issue by dorman99** [testdouble/testdouble.js#430]
Hay, iam new for using testdouble here. and i got stuck how can i create a test when a method of class calling the super, and using td.when on it.
let say, i have a class like this.
```
./Human.js 
 class Human {
    constructor(name, gender)
   eat(food, callback) {
     callback(null, food);
}
}

module.export = Human;

./Person.js
let Human = require('./human.js');
class Person extends Human {
    constructor(name, gender, age)
         super(name, gender)
    
     eat(food, callback) {
        super.eat(food, (err, eaten) => {
         callback(err, eaten);
});
     }
}
```

in my person_test.js
```
let Human = null;
let Person = null;
let chai = require('chai');
beforeEach((done) => {
    Human  = td.replace('../../Human.js');
    Person = require('../../Person.js');
    person = new Person('john', 'doe', 21);
  done();
})

describe( "On Test ", () => {
    it("Give 'apple', (done) => {
       person.eat('apple', (err, eaten) => {
       chai.expect(err).to.be.null;
       chai.assert.equal(eaten, 'apple');
      done();
})
})
})
```

limit exceeded after im trying to use this case.
ive done using td when before i called person.eat, to mock the response for the super one. but it still have no callback, and reacing the limit time. Am i missing something ? . please share something like this case. has been stuck like 2 days. thanks all.

**Comment by dorman99** [comment]
sorry, i miss something while reading the docs.

**Comment by searls** [comment]
No problem, thanks!
