### ISSUE TITLE
Adding Node-native ES Modules support

### ISSUE THREAD

**Issue by giltayar** [testdouble/testdouble.js#443]
`testdouble.js` currently supports CommonJS (CJS) only, and does not support the new native ESM support
in Node.js (unflagged from Node.js v13). I would like to add ESM support for this to testdouble.

Note that the feature in Node.js that is similar to require/Module hooks in CJS is called
[loaders](https://nodejs.org/api/esm.html#esm_experimental_loaders) and is highly experimental. As
an experiment, I built [`@giltayar/quibble-es`](https://github.com/giltayar/quibble-es) which uses
this Loader api to implement the [quibble API](https://github.com/testdouble/quibble/) for ESM.

It works, works simply, and works well! It can be used both from CJS files (`require`-ing it) and
from ESM files (`import`-ing it), but you need to add `--loader=@giltayar/quibble-es` (that is how loaders work: you need to specify them in the node command line).

The module is not _fully_ tested, and does not implement the _whole_ `quibble` API because if we want to add support to `testdouble`, I believe we should decide _how_ to do it before continuing here.

The options I see are:

1. Do a PR to `quibble` to incorporate the code from `quibble-es` so that `quibble` supports both
   CJS and ESM.
1. Do a PR to `testdouble.js` to import `quibble-es` and use both `quibble-es` and `quibble` in `testdouble.js`.

I much prefer the second option, but will defer to your decision. If the second
option _is_ chosen, I can migrate `@giltayar/quibble-es` into the `testdouble` Github user if that is a concern.

Open questions:

1. When replacing a module, `quibble-es` accepts a replacement for the default export and a separate object
   for the named exports because that is the natural interface for ESM. If we decide to merge
   `quibble-es` into `quibble`, do we keep that, and have two arguments that replace the module exports, or do
   something like if the replaced object has a `default` field than that is the default export.

1. Same question for `td.replace`? Do we continue with it for ESM (assuming a `default` property on
   the replacement stands for the default export replacement), or do we have a `td.replaceEsm`
   that accepts both the default replacement and the named exports replacement as two separate parameters.

Whatever options are chosen, I will gladly step up and implement them.

**Comment by jacobq** [comment]
There's [`td.replaceEsm` for this now, right](https://github.com/testdouble/testdouble.js/blob/main/CHANGELOG.md#3150)?

**Comment by searls** [comment]
LOL, yes. We're super good at closing old issues. Thanks!
