### ISSUE TITLE
Add td.instance(constructorFtn)?

### ISSUE THREAD

**Issue by woldie** [testdouble/testdouble.js#447]
### Description
Would like a one liner for when I don't need the mock constructor and just want a mock instance of a real constructor.

### Issue
What I do today:
```
let MockMarsRover = td.constructor(MarsRover);
let marsRover = new MockMarsRover();
```
where `MarsRover` is a constructor function.

What I'd _also_ like to be able to do:
```
let marsRover = td.instance(MarsRover);
```

@searls your "Please don't mock me" presentation was great!  725 slides, wew!!  Outside-In TDD is my jam.  I shared that prezzo with my agile coach friend and he switched from Sinon to testdouble.js immediately.

**Comment by searls** [comment]
Thanks for the kind words.

I think I'd be ok with a PR that implemented `td.instance` as described if it conformed to the style of the repo and had tests

**Comment by woldie** [comment]
Is this the correct way to run tests?

`npm run compile && npm run test`

**Comment by woldie** [comment]
twas merged

**Comment by searls** [comment]
Thanks for tidying this!

**Comment by woldie** [comment]
Sure, I wrote you another one though, heheh.  https://github.com/testdouble/testdouble.js/issues/467
