### ISSUE TITLE
Importing testdouble as an ES6 module

### ISSUE THREAD

**Issue by marktyers** [testdouble/testdouble.js#455]
### Description
I'm trying to import testdouble as an ES6 module.

### Issue
The module does not seem to support the ES6 module standard, there does not appear to be a default export.

```javascript
import td from 'testdouble'

SyntaxError: The requested module 'testdouble' does not provide an export named 'default'
```

### Environment

- [ ] `node -v` output: v14.13.1
- [ ] `npm -v` (or `yarn --version`) output: 6.14.8
- [ ] `npm ls testdouble` (or `yarn list testdouble`) version: 1.0.0

### Failing Test

- [ ] Fork the repo
- [ ] Add a failing test (probably to the `/regression/src' directory)
- [ ] Submit a pull request for the failing test or link to your branch here

### Example Repo

- [ ] Create a minimal repository that reproduces the issue
- [ ] Make sure that a fresh clone can run only `npm it` and observe the issue
- [ ] Link to that repo here

#### Runkit Notebook

- [ ] [Create a Runkit notebook](https://runkit.com/new)
- [ ] Invoke `var td = require('testdouble')` at the top
- [ ] Verify the behavior your issue is concerned with by clicking "Run"
- [ ] Link to the Runkit here

#### Code-fenced Examples

```js
var td = require('testdouble')

// Your steps here.
```

**Comment by searls** [comment]
If you want to use ES import syntax, pull in all of the top level functions with a wildcard:

```js
import * as td from 'testdouble'
```
