### ISSUE TITLE
`import`ing a native module after running `replaceEsm` on a native module breaks in node 14.13+

### ISSUE THREAD

**Issue by luxferresum** [testdouble/testdouble.js#457]
### Description
First, this works in node 14.12.

Basically this breaks:

```
await replaceEsm('fs');
await import('path');
```

with that error:

     Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:path?__quibble=2
      at Loader.builtinStrategy (internal/modules/esm/translators.js:266:11)
      at new ModuleJob (internal/modules/esm/module_job.js:38:41)
      at Loader.getModuleJob (internal/modules/esm/loader.js:245:11)
      at async Loader.import (internal/modules/esm/loader.js:164:17)
      at async Context.<anonymous> (file:///app/dist/test/framework/resources-test.js:34:5)

### Environment

- [x] `node -v` output: 14.13
- [x] `npm ls testdouble` (or `yarn list testdouble`) version: 3.16.1

### Example Repo
https://github.com/luxferresum/testdouble-esm-test

**Comment by searls** [comment]
Hey @giltayar can you look at this?

**Comment by giltayar** [comment]
Interesting. Some backward incompatible change in loaders, probably. @luxferresum Thanks for investigating, and will check it out!

**Comment by giltayar** [comment]
OK, the tests of `quibble` (which is the lower level library used by `testdouble` to do the actual mocking) fail on 14.13 and later, so I have a repro with the existing tests. Definitely makes it easier, and gives me confidence that our tests are good! :-)
