### ISSUE TITLE
using td.object resolves in SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by lavor** [testdouble/testdouble.js#459]
### Description

After upgrade from 3.14.0 to 3.15.0 the usage of `td.object` will break down a test. Maybe there is a corrupted file `node_modules/testdouble/lib/imitate/overwrite-children/gather-props.js`?
### Issue

I upgraded testdouble from version 3.14.0 to the current version 3.16.1. My previously working tests start to fail.
```
SyntaxError: Unexpected identifier
      at Object.exports.default (node_modules\testdouble\lib\imitate\overwrite-children\index.js:15:60)
      at Object.imitate (node_modules\testdouble\lib\imitate\index.js:12:33)
      at fakeObject (node_modules\testdouble\lib\object.js:20:33)
      at Object.object (node_modules\testdouble\lib\object.js:10:33)
```
After some debugging I found out that the problem part in my test is the usage of `td.object`:
```js
const tdProjectConfigState = td.object({
    isLoaded: () => {
    }
});
```
After downgrade back to version 3.14.0, everything works perfectly.

Weird is that when I put some `console.log()` to the file `node_modules/testdouble/lib/imitate/overwrite-children/gather-props.js` everything works perfectly also in version 3.16.1.

The problem starts to happen in version 3.15.0.

The quick fix after upgrade to version 3.16.1 which works for me is to touch the problem file `gather-props.js`:
```
npm i -D testdouble@3.16.1
// tests starts to fail
touch node_modules/testdouble/lib/imitate/overwrite-children/gather-props.js
// tests works again
```

### Environment

- [x] `node -v` output: v12.18.3
- [x] `npm -v` (or `yarn --version`) output: 6.14.6
- [x] `npm ls testdouble` (or `yarn list testdouble`) version: -- testdouble@3.15.0

#### Code-fenced Examples

```js
var td = require('testdouble')

//...

it('should work', function() {
    // this code resolves in a SyntaxError: Unexpected identifier
    const tdProjectConfigState = td.object({
        isLoaded: () => {
        }
    });
});

//...
```

**Comment by searls** [comment]
Can you confirm that this problem persists even after you blow away your installation of testdouble.js (e.g. `rm -rf node_modules`) and reinstall?

**Comment by lavor** [comment]
Hi, @searls,
yes, I uninstalled testdouble, installed it again and it did not work again:

```bash
npm un testdouble
npm i -D testdouble@3.16.1
# tests start to fail
touch node_modules/testdouble/lib/imitate/overwrite-children/gather-props.js
# tests work again

npm un testdouble
npm i -D testdouble@3.14
# tests work again

npm un testdouble
npm i -D testdouble@3.15
# tests start to fail
touch node_modules/testdouble/lib/imitate/overwrite-children/gather-props.js
# tests work again
```

Now I tried to remove node_modules completely as you suggested and it helps, but only for a moment. Maybe there was something still cached after uninstalling. Then I tried to install previously working version 3.14 and now it did not work either?!

```bash
rm -rf node_modules
npm i
npm list testdouble # `-- testdouble@3.16.1
# tests work again

npm i -D testdouble@3.14
npm list testdouble # `-- testdouble@3.14.0
# tests start to fail!
# trying to touch OTHER file then gather_props.js
touch node_modules/testdouble/lib/imitate/overwrite-children/copy-props.js
# tests still fail
touch node_modules/testdouble/lib/imitate/overwrite-children/gather-props.js
# tests work again

# trying to install latest (3.16.1 version, as it was installed with npm i above)
npm i -D testdouble@3.16.1
# tests work again!
```

Though, I don't understand what there happens. Is that file gather-props.js something special, different encoding, ...?

**Comment by searls** [comment]
Closing this without a specific diagnosis or other reproductions. I've dug into all the files in the git repo and in the npm tarball and can't find anything wrong with its ACL, invisible characters, etc. Sorry!
