### ISSUE TITLE
How to ensure that a function was called once and only once in typescript

### ISSUE THREAD

**Issue by vpillinger** [testdouble/testdouble.js#460]
### Description
I need to ensure that a function is called once and only once. In this case I am testing a system that sends notifications based on insert/update/deletion of models. For example, I need to test my system only fires a "delete" event when a model is deleted, and not an "update" event. However, in Typescript it does not seem possible to check that this is the case as it would require me to pass 0 arguments to a function that requires arguments.

### Issue

There does not appear to be a way to verify that a specific invocation of a method was the only invocation.

#### Runkit Notebook

https://runkit.com/vpillinger/testdouble-times

#### Typescript code

```
I tried casing to <any> but this doesn't work.
function myTest(queue) {
  queue.publish('good to go');
  queue.publish('o no, extra events');
}
queue = td.object({publish: function(){}});
myTest(queue);

// does not compile
td.verify(queue().publish(), { times: 1 });

// does not error
td.verify((<any>queue()).publish(), { times: 1 });
// oddly, this does error
td.verify((<any>queue()).publish(), { times: 10 });

// does not error
td.verify(queue().publish(undefined), { times: 0 });
```

**Comment by searls** [comment]
In my practice, it is very rare that this assertion is truly [necessary](https://blog.testdouble.com/posts/2020-02-25-necessary-and-sufficient/#necessary-tests).

When it is, you can assert that `td.explain(foo).callCount` is === 1:

```js
const foo = td.func();

foo();

td.explain(foo).callCount
```
