### ISSUE TITLE
Switch global to globalThis

### ISSUE THREAD

**Issue by NullVoxPopuli** [testdouble/testdouble.js#471]
### Description

This is a bit of a resurrection of: https://github.com/testdouble/testdouble.js/issues/438, in that browsers are not able to use testdouble.js without a `global` "polyfill", like the following:
```html
<script>
    // testdouble doesn't natively support the browser as it assumes
    // that a `global` identifier will be available, but that is not the case for browsers
    window.global = globalThis;
</script>
```

Just checking the compatibility table over here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

it looks like globalThis is supported everywhere that matters? 

Is it possible to drop usage of `global`?

This is probably also related to: https://github.com/testdouble/testdouble.js/issues/434

### Environment

- [ ] `node -v` output:
- [ ] `npm -v` (or `yarn --version`) output:
- [ ] `npm ls testdouble` (or `yarn list testdouble`) version:

Chrome and Firefox v90+

importing testdouble causes an error, because of [this code](https://github.com/testdouble/testdouble.js/blob/65d7023b2f1c9084cdd7cd288550aa4ab68495bf/src/config.js#L5-L9): 

```
const DEFAULTS = {
  ignoreWarnings: false,
  promiseConstructor: global.Promise,
  suppressErrors: false
};
```

**Comment by searls** [comment]
Seems good

**Comment by rosston** [comment]
We might want to drop [support for Node 10](https://github.com/testdouble/testdouble.js/blob/7e0dc89a4ab899eb2e8b6ab91fe88011d88f0df6/.circleci/config.yml#L35) at the same time. If I'm tracking my Node changes correctly, v10 went EOL on 2021-04-30.
