### ISSUE TITLE
Modules getting picked from cache

### ISSUE THREAD

**Issue by ankitkhedekar** [testdouble/testdouble.js#489]
### Description
Test cases are picking the required subject module from the cache. Hence they don't get the mocked instances of functions/modules that have been replaced using `td.replace()`. 

Manually deleting the entry from `require.cache` solves it. And the next `require()` call correctly picks up the mocked references. Also such issues occur only when the entire test suite is run, running individual tests don't seem to cause such problems

### Issue: General question

As per this [section](https://github.com/testdouble/testdouble.js/#module-replacement-with-nodejs) in docs, having `td.replace() ` and `require()` in the beforeEach() block bypasses module cache, but for some reason this doesn't seem to work in my setup

```
// test.js

// other tests

describe('Testing module A', () => {
  let depModule, subject
  beforeEach(() => {
    depModule = require('path/to/depModule')
    let mockedFn = td.replace(depModule, 'depFn')
    subject = require('path/to/subjectModule') // refers to original depFn
  })
  afterEach(() => {
    td.reset()
  })
 // it blocks
)

```

To fix this I am currently maunally deleting references from require.cache. Like below:
```
beforeEach(() => {

  /** hacky workaround */
  delete require.cache[require.resolve('path/to/subjectModule')]


  depModule = require('path/to/depModule')
  let mockedFn = td.replace(depModule, 'depFn')
  subject = require('path/to/subjectModule') // refers to mocked depFn
})

```

I would like to understand in such cases what is the cause usually? and if any there are better ways to deal with it?

P.S.: Please correct me if this is not the correct channel for queries

**Comment by searls** [comment]
This is caused because `td.replace` is meant to be called INSTEAD of calling `require` on whatever dependency is faked.

That is to say, I would replace this:

```js
    depModule = require('path/to/depModule')
    let mockedFn = td.replace(depModule, 'depFn')
```

With:

```js
  depModule = td.replace(depModule, 'depFn')
```
