### ISSUE TITLE
replaceEsm not working on windows

### ISSUE THREAD

**Issue by connorjclark** [testdouble/testdouble.js#491]
### Description

ES modules are not mocked on windows. Works fine on Mac.

### Environment

- [ ] `node -v` output: 14.8.2
- [ ] `yarn --version` output: 1.22.19
- [ ] `npm ls testdouble` (or `yarn list testdouble`) version: 3.16.15

### Example Repo

https://github.com/connorjclark/testdouble-win-example

```js
// main.js
import * as td from 'testdouble';

td.replaceEsm('./module.js', {runMe: () => 'replaced'});

const {runMe} = await import('./module.js')

console.log(runMe());
```

```js
// module.js
export function runMe() {
    return 'original';
}
```

`node --loader=testdouble main.js` prints `original` on windows, `replaced` on Mac.

**Comment by searls** [comment]
Paging @giltayar if he might have any insight 🙏

**Comment by connorjclark** [comment]
![image](https://user-images.githubusercontent.com/4071474/177057604-346ec0b5-e533-41fa-ac22-14950aaca1af.png)

The key in the global modules Map duplicated `C:/` for some reason.

**Comment by connorjclark** [comment]
I made the following change inside quibble to fix, which resolved the bug:

![image](https://user-images.githubusercontent.com/4071474/177058677-a9cd9787-e77a-4eb6-9fc1-aa9fda61e04e.png)

```
if (process.platform === 'win32') {
    fullModulePath = callerFile.replace('/C:', 'C:')
    fullModulePath = path.resolve(path.dirname(fullModulePath), importPath)
    fullModulePath = '/' + fullModulePath.split(path.sep).join("/")
  }
```

Of course, I shouldn't be hardcoding the drive there. But anyway, the real fix is probably something to do with correctly juggling the format of the Error filename / module name / URLs being passed around, being mindful of Windows's differing slashes / existence of a drive suffix.

**Comment by searls** [comment]
Thanks for digging into this. Ultimately, if you (or another developer that uses Windows) might consider sending a PR with a test for this that they can assert works OK on windows without breaking anything else, I'd be eager to accept it.

**Comment by giltayar** [comment]
Cloned your repo, updated testdouble to the latest version, and added an `await` before `td.replaceEsm`. Got the correct result ("replaced"), so closing this issue.
