### ISSUE TITLE
Add verify times()

### ISSUE THREAD

**Issue by searls** [testdouble/testdouble.js#5]
Once #4 is added, then consider adding:

```
verify(testDouble("lol"), times: 18)
```

To ensure this verification was satisfied 18 times.

**Comment by mweitzel** [comment]
+1, especially for asserting 0 times.

**Comment by searls** [comment]
I'd like to support as many options as possible for both `when` and `verify`. Keeping their APIs symmetrical is important to me, because it's so hard for end-users to keep the two functions straight.

So, for `verify`, it should verify that the callCount is what was said. For `when`, I suppose `times` should stop matching the stubbing at all if the call count exceeds `times`

**Comment by searls** [comment]
Hey @mweitzel this landed in 0.5.0 just now

**Comment by mweitzel** [comment]
Sweet, thanks. I'll check it out.
