### ISSUE TITLE
Incompatibility with node v20.0.0

### ISSUE THREAD

**Issue by stixx200** [testdouble/testdouble.js#513]
### Issue

I wan't to get testdouble working on Node.js v20.0.0
Node.js v20.0.0 introduces a segregation of loader code and production code
In the changelog, they call it "Loader hooks are executed off the main thread" (https://nodejs.org/api/esm.html#modules-ecmascript-modules)

With this segregation, it is only possible to communicate via a messagePort with the loader. But this only allows to send copied values, no shared objects or modules.

Is there a way to run testdouble.js with Node v20.0.0?

### Environment

- [x] `node -v` output: v20.0.0
- [x] `npm -v` (or `yarn --version`) output: npm 9.6.4
- [x] `npm ls testdouble` (or `yarn list testdouble`) version: testdouble@3.17.2

### Example Repo

```js
// test.js
import * as td from 'testdouble';

await td.replaceEsm('./foo.js', { foo: () => "foomocked" });

const { print } = await import("./other.js");
print();
```
```js
// other.js
import { foo } from "./foo.js";

export function print() {
    console.log("imported", foo());
}
```
```js
// foo.js
export const foo = () => "foo.js"
```

**Comment by giltayar** [comment]
Note that `20.0.0` will not work, even after quibble is fixed, because it broke loaders. Use `20.1.0` and above.

(PR to `quibble` to support Node 20 comin' right up!)
