### ISSUE TITLE
replaceEsm breaks in node20 when other loaders are used

### ISSUE THREAD

**Issue by jalfd** [testdouble/testdouble.js#525]
### Description
I'm trying to use testdouble in a Typescript project using ESM modules, and I get a `TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts` error when I try to use the replaceEsm function.

### Issue

Assume a source file like the following, which tries to use replaceEsm before importing another typescript module, `other.ts`:
```
import * as td from "testdouble";

await td.replaceEsm("fs");
await import("./other.js");
```

If I run this under a typescript loader like `tsx` or `ts-node/esm`, I get an error like the following:

```
> repro@1.0.0 withtestdouble
> tsx withtestdouble.ts

node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/jalf/src/repro/other.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
    at defaultLoad (node:internal/modules/esm/load:143:22)
    at async nextLoad (node:internal/modules/esm/hooks:750:22)
    at async Z (file:///Users/jalf/src/repro/node_modules/tsx/dist/esm/index.mjs:5:1644)
    at async nextLoad (node:internal/modules/esm/hooks:750:22)
    at async load (file:///Users/jalf/src/repro/node_modules/quibble/lib/quibble.mjs:140:7)
    at async nextLoad (node:internal/modules/esm/hooks:750:22)
    at async Hooks.load (node:internal/modules/esm/hooks:383:20)
    at async MessagePort.handleMessage (node:internal/modules/esm/worker:199:18) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

If remove the replaceEsm call, it works fine.

Apparently the tsx and quibble loaders clash, somehow.

### Environment

- `node -v` output: v20.9.0
- `npm -v` (or `yarn --version`) output: 10.1.0
- `npm ls testdouble` version: testdouble@3.20.1

### Example Repo
https://github.com/jalfd/testdouble-repro

- run `npm run withtestdouble` to reproduce the problem.
- run `npm run notestdouble` to see that it works if the replaceEsm call is removed

**Comment by codan84** [comment]
I use testdouble with ava and it seems to work on node 20.
Initially it started failing after upgrading to node 20, but switching loader `ts-node/esm` to `--import=tsimp/import` for TypeScript worked.
https://www.npmjs.com/package/tsimp
I appreciate you might not be using Ava, but this might help with whatever other test framework you are using.

**Comment by JakobJingleheimer** [comment]
This is almost surely caused by the testdouble loader's `resolve` hook stomping other loaders' resolve hooks (perhaps a short-circuit?). This is the case for https://github.com/JakobJingleheimer/nodejs-loaders:

```console
node --loader=testdouble --loader=nodejs-loaders/dev/tsx ./main.mts
```

```js
// main.mts

import './foo.mts'; // the contents of foo.mts doesn't matter
```

```console
node --loader=testdouble --loader=nodejs-loaders/dev/css-module ./main.mjs
```

```js
// main.mjs

import './foo.module.css'; // the contents of foo.module.css doesn't matter
```

These work fine when `--loader=testdouble` is removed.

**Comment by JakobJingleheimer** [comment]
I believe the issue may be caused by 
https://github.com/testdouble/quibble/blob/main/lib/quibble.mjs#L58
https://github.com/testdouble/quibble/blob/main/lib/quibble.mjs#L66

There is more output from `await resolve()` than just `url`, and that omitted output must be included in the return:

```patch
  try {
-    const { url } = await resolve()
+    const { format, importAttributes, url } = await resolve()

    const quibbledUrl = addQueryToUrl(url, '__quibble', stubModuleGeneration)

    if (url.startsWith('node:') && !getStubsInfo(quibbledUrl)) {
      return { url }
    }

-    return { url: quibbledUrl }
+    return { format, importAttributes, url: quibbledUrl }
  } catch (error) {
```

**Comment by JakobJingleheimer** [comment]
AH! No, those changes are needed, but they are not the cause. Quibble's query params dupe node's `path.extname` (et al): `path.extname('foo.mts?__quibble=0')` → `'.mts?__quibble=0'`
