### ISSUE TITLE
Allow argument matchers to enhance failure messages

### ISSUE THREAD

**Issue by searls** [testdouble/testdouble.js#59]
I was a little disappointed by this:

``` javascript
eatBiscuit(44)

td.verify(eatBiscuit(td.matchers.isA(Date)))

Error: Unsatisfied verification on test double.

  Wanted:
    - called with `({})`.

  But was actually called:
    - called with `(44)`.
```

It really seems like the `isA` matcher should have and use a hook to report something such that we'd see:

```
  Wanted:
    - called with `([something of type 'Date'])`.
```

**Comment by searls** [comment]
(The same goes for all the built-in matchers; the real work here is the hook to modify the argument description)

**Comment by samjonester** [comment]
This looks like it's already completed, unless there is more you'd like to include with this ticket:

https://github.com/testdouble/testdouble.js/blob/master/src/stringify/anything.coffee#L13
https://github.com/testdouble/testdouble.js/blob/master/src/matchers/index.coffee#L21

**Comment by searls** [comment]
Do we have a test for something like I pointed out at the top?

**Comment by samjonester** [comment]
is https://github.com/testdouble/testdouble.js/blob/master/test/src/verify-test.coffee#L97 sufficient?

**Comment by searls** [comment]
This was indeed fixed when we changed the matchers format to have a `name` property.
