### ISSUE TITLE
Feature request: captors without verify

### ISSUE THREAD

**Issue by artlogic** [testdouble/testdouble.js#65]
Forgive me if this isn't the appropriate place for feature request.

I've been writing a bunch of tests that involve the use of captors. I've found it's a little odd to use verify to capture the value of an anonymous function - especially when what you are verifying isn't really under test. For instance:

```javascript
// verify callback is eventually called
var callback = td.function(), error = new Error(), data = {};
var captor = td.matchers.captor();

// calls mock.api with a argument and an anonymous function (that should invoke callback)
subject.delete(callback);

// capture the anonymous function (not a real verification), and call
td.verify(mock.api(td.matchers.anything(), captor.capture()));
captor.value(error, data);

// the REAL verification
td.verify(callback(error, data));
```

It struck me that this style might be a bit clearer:

```javascript
// verify callback is eventually called
var callback = td.function(), args, anon, error = new Error(), data = {};

// calls mock.api with a argument and an anonymous function (that should invoke callback)
subject.delete(callback);

// capture the anonymous function and call
args = td.capture(mock.api);
anon = args.slice(-1);  // use the last argument
anon(error, data);

// verify
td.verify(callback(error, data));
```

To me this reads a bit more clearly, because I say what I'm doing - capturing the arguments that double was previously called with. It's entirely possible my assumptions are a bit off. I've only been using testdouble.js for 4 hours or so.

**Comment by searls** [comment]
Starting off, when I read:

> I've been writing a bunch of tests that involve the use of captors.

I immediately get worried that this might be a smell of either an awkward design choice or that captors are scratching an itch for you that the library could serve in a better way. Most functions shouldn't need captors. 

My suspicion is that for the type of function you're writing, better callback-style-API support is what we really want, as opposed to tweaking the captor matcher API. (See #66).

To start, could you reply with the `subject.delete` implementation you were trying to specify so I can take a stab at it?

**Comment by artlogic** [comment]
Here's what my `subject.delete` looks like:

```javascript
delete: function (userId, callback) {
  if (typeof userId === 'function') {
    callback = userId;
    userId = state.userId;
  }

  core.api('DELETE', '/user/${userId}', {
    userId: userId
  }, undefined, function (error, data) {
    if (state.userId === userId) {
      // if the user deleted their own account, logout
      core.auth.logout();
    }

    callback(error, data);
  });
}
```

Here's the test I wrote:

```javascript
it('should call logout if userId === state.userId', function () {
  var any = td.matchers.anything();
  var captor = td.matchers.captor();

  user.delete(function () { });

  // capture the anonymous function (not a real verification), and call
  td.verify(core.api(any, any, any, any, captor.capture()));
  captor.value();

  td.verify(core.auth.logout());
});
```

I've got a lot of similar functions. I've written a lot of similar tests to support them. I'm fairly new at this style of TDD - it could be there are better ways to accomplish what I'm doing. I'm open to suggestions.

**Comment by searls** [comment]
This has been roundaboutly solved since you opened the issue with the introduction of the `thenCallback` API. Check out this example below, which simplifies your subject function a bit to illustrate the point:

``` js
//The "real" core:
var core = { api: function(){} }

// Your subject:
function deleteUser(userId, callback) {
  core.api('DELETE', function(error, data) {
    callback(error, data + ' for ' + userId)
  })
}


td.replace(core, 'api')
var cb = td.function()
td.when(core.api('DELETE')).thenCallback('an err', 'an data')

deleteUser(55, cb)

td.verify(cb('an err', 'an data for 55'))


```
