### ISSUE TITLE
Reserved word

### ISSUE THREAD

**Issue by colindresj** [testdouble/testdouble.js#82]
`function` is a reserved word. I think it would be prudent to deprecate `td.function()` in favor of some other method name, perhaps `td.func()`.

The way the source is currently written, everything is actually valid. `function` is being used as an `IdentifierName`, which has no problem with reserved words:

```coffee
module.exports =
  function: require('./function')
```

However if someone were to do something like this, they'd get a syntax error:

```js
const td = require('test-double');
const { function } = td; // raises an exception
```

I feel like the above will become a fairly common use case, so by changing the method name to something that can be destructured into an `Identifier` without a reserved word clash would save some headaches:

```js
const td = require('test-double');
const { func } = td; // this works
```

Of course, if someone wanted to destructure with the current name they could do it:
```js
const { function: func } = td;
```

But I feel like that is forcing people into doing something for the sake of lexical compatibility instead of expressiveness, which is, I think, the use case for destructed re-assignment.

Anyways, this is just a suggestion. I understand it could introduce some backwards compatibility problems.

**Comment by searls** [comment]
I'm not opposed to this if we can gather data on people actually experiencing it as a problem. There are scant few cases when someone would ever want to import just one method on the module, so I'm not really convinced that hypothetical concern is going to be people's lived experience. 

I did some research and edge case testing when I renamed `create` to `object` and `function`, and was surprised to find that it didn't really cause any issues, despite being a reserved word.

**Comment by colindresj** [comment]
Yeah, the only real time I see this becoming a problem is with destructuring. I agree that most people won't grab just one method, but I do see myself, at least, doing something like:

```js
const {
  func,
  when,
  verify,
  matchers,
  reset
} = require('test-double');

const fetch = func();

when(fetch(42)).thenReturn('Jane User');

fetch(42);

verify(fetch(matchers.isA(Number));
assert(explain(fetch).callCount, 1);

reset();
``` 

I personally like the readability of just `verify`, `reset`, etc. as opposed to `td.verify`, `td.reset`. Not sure how many other people feel this way, but I'll leave it up to you to close or keep open this issue.

As a second, less legitimate reason, `td.function` causes a lot of syntax highlighters to pick up on the word and color it different to other object properties.

**Comment by searls** [comment]
How would you feel about simply adding func as an alias?

**Comment by colindresj** [comment]
Yeah that sounds like a pretty good idea to me.
