### ISSUE TITLE
td.replace() fails for method on prototype

### ISSUE THREAD

**Issue by Turbo87** [testdouble/testdouble.js#86]
```js
var td = require('testdouble');

var Foo = function() {
  console.log('foo');
};

Foo.prototype.bar = function() {
  console.log('bar');
};

var foo = new Foo();

var bar = td.replace(foo, 'bar');

bar();
```

results in

```
Error: td.replace error: No "bar" property was found.
```

which is most likely related to the use of the `hasOwnProperty()` function to check if the property exists.

**Comment by searls** [comment]
I struggle to imagine a good situation to stub out a single function of an instance of a constructed object, as you're effectively creating a [partial mock](https://github.com/testdouble/contributing-tests/wiki/Partial-Mock). Can you point out an example usage that wouldn't be effectively adding support for partial mocks?

**Comment by searls** [comment]
By the way, I'm definitely open to allowing this. 

Given that JavaScript lacks strong conventions about when to use a plain object versus a constructor-instantiated object, the distinction (which matters a great deal in, say, Ruby or Java) may not be as meaningful here.

**Comment by Turbo87** [comment]
@searls just for completeness:

in `ember-cli` we have a `Ui` class with stuff like `logWarning()` and `logError()` and a `MockUi` subclass that is used in tests that will not do `console.log()` but rather save the output in an array for assertions later. that `Ui` class also has a `prompt()` method which we would like to `td.replace()` on the `MockUi` instances to make sure it gets called properly. as you might guess we don't want to `td.replace()` the whole `MockUi`class because some convenience methods of the original `Ui` class should stay intact.

I hope that description was somewhat understandable. I'm happy to discuss alternative approaches if you think they exist.
