### ISSUE TITLE
td.replace() fails when dependency is cached

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [testdouble/testdouble.js#89]
I have the following code that depends upon `./open-repository` module:

**git-commit.js**
```javascript
const root = require("app-root-path");

const openRepository = require(root + "/src/git/open-repository");

module.exports = function() {
  openRepository("./");
};
```

The following test check if the `openRepository` function is called with the `"./"` arguments:

**git-commit.spec.js**

```javascript
const root = require("app-root-path");
const td = require("testdouble");

const gitCommit = require(root + "/src/routines/git-commit");

describe("git-commit", function() {
  "use strict";
  let openRepository;

  beforeEach(function() {
    openRepository = td.replace(root + "/src/git/open-repository");
  });

  afterEach(function(){
    td.reset();
  });

  it.only("should validate Github credentials", function() {
    gitCommit("Release version 0.0.1");
    td.verify(openRepository("./"));
  });

});
```

Unfortunately it fails with the following message:

```shell
1) git-commit should validate Github credentials:
     Unsatisfied verification on test double `/Users/fagnerbrack/Git/js-cookie-build/src/git/open-repository`.

  Wanted:
    - called with `("./")`.

  But there were no invocations of the test double.
  Error: Unsatisfied verification on test double `src/git/open-repository`.
  
    Wanted:
      - called with `("./")`.
  
    But there were no invocations of the test double.
      at Object.module.exports [as verify] (node_modules/testdouble/lib/verify.js:22:15)
      at Context.<anonymous> (test/unit/routines/git-commit.spec.js:22:8)
```

If I change **git-commit.js** like this, it works successfully:

```javascript
const root = require("app-root-path");

module.exports = function() {
  const openRepository = require(root + "/src/git/open-repository");
  openRepository("./");
};
```

(Note that the `require(root + "/src/git/open-repository");` is inside the `module.exports` declaration).

Is that the expected behavior? If so, can the `td.replace()` docs highlight why this doesn't work?

**Comment by searls** [comment]
Apologies, I'm on vacation and won't be able to look at it until next week. 

It'd be a great help if you could open an issue on quibble itself with a minimal reproducible example (or even a test case)

**Comment by searls** [comment]
I haven't had a chance to play with your code examples, but based on my reading of it, you need to call `require()` of your subject after you've called `td.replace()` on its dependencies. If you `require()` the subject before ever having called `td.replace()`, then `quibble` (the module which provides this functionality) won't have any opportunity to patch `Module._load` that it needs to bypass the cache when `require()` is invoked for the subject.

I would have expected the test to be written like this:

``` js
const root = require("app-root-path");
const td = require("testdouble");

describe("git-commit", function() {
  "use strict";
  let openRepository, gitCommit;

  beforeEach(function() {
    openRepository = td.replace(root + "/src/git/open-repository");
    gitCommit = require(root + "/src/routines/git-commit");
  });

  afterEach(function(){
    td.reset();
  });

  it.only("should validate Github credentials", function() {
    gitCommit("Release version 0.0.1");
    td.verify(openRepository("./"));
  });

});
```

**Comment by FagnerMartinsBrack** [comment]
Thank you for the clarification and sorry for not being able to track down this issue further to the root. In the meantime do you think it might be worth pointing this out in the docs?

This is only noticeable by someone who knows how the internals of the API and the internals of node works, therefore a clear abstraction leak from the limitations of the underlying technologies.

Thanks!
