### ISSUE TITLE
td.replace() property replacement warning & failure states

### ISSUE THREAD

**Issue by searls** [testdouble/testdouble.js#92]
Inspired by #86, just thinking out loud:

Property replacement should fail if:
- [x] The property does not exist and no manual replacement is passed
- [x] The property exists, no manual replacement is passed, and `imitate` doesn't know how to handle its type (currently imitate will return a `td.function` even if the property is something strange like a `String`, `Number`, `null`, etc.

Property replacement should warn if:
- [x] The property exists, manual replacement is used, and the type of the replacement doesn't match the type of replacement being passed

Is the added failure state a "breaking" change worthy of a major bump?

**Comment by jasonkarns** [comment]
> Is the added failure state a "breaking" change worthy of a major bump?

I don't think so. Present behavior isn't a "supported" use case of `replace` so I would consider this a new feature, if anything.

**Comment by searls** [comment]
Landed in 1.3.0
