### ISSUE TITLE
What's the best way to use testdouble.js with tape?

### ISSUE THREAD

**Issue by d6u** [testdouble/testdouble.js#93]
I saw https://github.com/testdouble/testdouble.js/issues/33 but it's quite verbose to use testdouble with tape:

```js
const test = require('tape');
const td = require('testdouble');

test('verify invoked', function(t) {
  t.plan(1)

  var stub = td.create()

  stub('any arguments', 0, 1, 2)

  t.doesNotThrow(function() {
    td.verify(stub0())
  }, 'called with more arguments when none are specified')
})
```

Anyway to not pass a callback to `t.doesNotThrow`?

Thanks!

**Comment by searls** [comment]
Forgive my naivety, but what does tape do when a function passed to `test` throws an error. I presume it fails the test, right? If so, why not:

``` js
const test = require('tape');
const td = require('testdouble');

test('verify invoked', function(t) {
  t.plan(1)

  var stub = td.create()

  stub('any arguments', 0, 1, 2)

  td.verify(stub0())
})
```

**Comment by d6u** [comment]
@searls Because we called `t.plan(1)`, tape expect have one assertion method called, which was `t.doesNotThrow`. Since we are not calling assertion in your example, tape will complaint about it. The rest should work though.

**Comment by Schoonology** [comment]
@d6u, can you use `t.end()` at the end of your test in lieu of using `t.plan()` at the beginning?

**Comment by Schoonology** [comment]
That's right. I meant more like this:

```js
const test = require('tape');
const td = require('testdouble');

test('verify invoked', function(t) {
  var stub = td.create()

  stub('any arguments', 0, 1, 2)

  td.verify(stub())

  t.end()
})
```

Does that work for your situation?

**Comment by d6u** [comment]
This should work. Thanks. To push this further, could testdouble.js hook up with tape and let tape count each `verify()` towards `plan`? If this is not possible now, what does it take to develop a plug in myself?

**Comment by searls** [comment]
We have a couple other plugins that hook `verify` into assertion libs and I suspect this should also be possible. See testdouble-chai and testdouble-jasmine for reference

**Comment by d6u** [comment]
Thanks

**Comment by searls** [comment]
Because `td.verify` throws an error, one option might be to use tape-catch: https://github.com/michaelrhodes/tape-catch

**Comment by customcommander** [comment]
If you really want to use `t.plan(…)` then what I would do is something like that:

```javascript
const test = require('tape');
const td = require('testdouble');
const SUT = require(/* … */); // Subject Under Test

test('Hello World!', t => {
  t.plan(1);
  const fn = td.func();
  SUT(fn, 42);
  td.verify(fn(42));
  t.pass('fn was applied to 42'); // <-- Counts towards t.plan
  t.end();
});
```

TAP Output:

```none
# Hello World!
ok 21 fn was applied to 42
```
